function s = buildEDSPanel(parent, tk, palette, callbacks)
%BUILDEDSPANEL  Construct the EDS Channels sub-panel for FermiViewer.
%
% Syntax
%   s = fermiViewer.eds.buildEDSPanel(parent, tk, palette, callbacks)
%
% Inputs
%   parent     uigridlayout (toolsGL) that hosts the panel.
%              The function creates pnlEDS inside parent and sets
%              its Layout.Row = 12.
%   tk         UX tokens struct (unused here, reserved for future theming)
%   palette    struct of semantic button colours:
%                .primary  — green, primary actions
%                .tool     — gray, secondary tools
%                .danger   — red, destructive actions
%                .export   — blue, export actions
%                .fg       — white foreground text
%   callbacks  struct of function handles:
%                .onEnterEDS             — Enter EDS mode toggle
%                .onEDSListChange        — dispatches 'add' or 'remove'
%                .onEDSChannelSelected   — channel list selection changed
%                .onEDSChannelPropChanged — dispatches 'color', 'visible',
%                                          'intensity', 'label'
%                .onExportEDSComposite   — export blended RGB composite
%                .onAssignElements       — assign element symbols to channels
%                .onQuantifyCL           — Quantify (Method-dropdown driven)
%                .onCompositionProfile   — line composition profile
%                .onROIComposition       — ROI mean composition
%                .onQuantifyZAF          — ZAF-corrected quantification
%
% Outputs
%   s   struct of widget handles:
%         .pnlEDS               — the outer uipanel (parented to toolsGL)
%         .btnEnterEDS          — Enter/Exit EDS mode button
%         .btnAddChannel        — Add Channel button
%         .btnRemoveChannel     — Remove channel button
%         .lbEDSChannels        — channel list box
%         .EDS_COLORS           — cell array of available colour names
%         .ddChannelColor       — channel colour dropdown
%         .cbChannelVisible     — channel visibility checkbox
%         .lblEDSIntensity      — intensity value label
%         .sldChannelIntensity  — channel intensity slider
%         .efChannelLabel       — channel label edit field
%         .btnExportComposite   — Export RGB button
%         .btnAssignElements    — Assign Elements button
%         .btnQuantifyCL        — Quantify button (Method dropdown driven)
%         .ddEDSMethod          — Quantification method dropdown:
%                                 'Window integration' (default) | 'Peak fit'
%                                 | 'ζ-factor' — read by
%                                 fermiViewer.eds.runQuantifyCL via Tag lookup
%         .cbEDSRemoveArtifacts — Escape/sum artifact pre-pass checkbox
%                                 (default off; Tag 'cbEDSRemoveArtifacts')
%         .ddEDSMapBackground   — Element-map background model for
%                                 fermiViewer.eds.buildCubeChannels:
%                                 'none' | 'linear' (default) |
%                                 'bremsstrahlung' (Tag 'ddEDSMapBackground')
%         .edtEDSE0KeV          — Beam energy override (keV) for the
%                                 bremsstrahlung background; blank uses
%                                 beam-energy metadata when present
%                                 (Tag 'edtEDSE0KeV')
%         .edtEDSDoseCurrentNA  — ζ-factor probe current, nA (Tag
%                                 'edtEDSDoseCurrentNA')
%         .edtEDSDoseLiveTimeS  — ζ-factor acquisition live time, s (Tag
%                                 'edtEDSDoseLiveTimeS')
%         .edtEDSZetaSi         — ζ-factor absolute Si-Kα standard, kg/m^2
%                                 (Tag 'edtEDSZetaSi')
%         .btnCompositionProfile — Composition Profile button
%         .btnROIComposition    — ROI Composition button
%         .edtEDSThickness      — specimen thickness edit field
%         .edtEDSTakeOff        — take-off angle edit field
%         .btnQuantifyZAF       — Quantify ZAF button
%
%   The Method/Artifact/Background/Dose controls added alongside the
%   Quantify button postdate fermiViewer.eds.dispatch's ctx struct
%   (buildEDSCtx() in FermiViewer.m only carries the original handles), so
%   package-side consumers (fermiViewer.eds.runQuantifyCL,
%   fermiViewer.eds.dispatch) locate them via Tag + findobj through
%   ctx.btnQuantifyCL.Parent (the shared edsInnerGL grid) rather than
%   through new ctx fields. See runQuantifyCL.m's resolveEDSOptions.
%
% Examples
%   eds_ = fermiViewer.eds.buildEDSPanel(toolsGL, struct(), palette, callbacks);
%   btnEnterEDS = eds_.btnEnterEDS;

    arguments
        parent
        tk         struct  %#ok<INUSA>  % reserved for future theming
        palette    struct
        callbacks  struct
    end

    % Palette shorthands
    BTN_PRIMARY = palette.primary;
    BTN_TOOL    = palette.tool;
    BTN_DANGER  = palette.danger;
    BTN_FG      = palette.fg;

    % ── Outer panel (parented to toolsGL, row 12) ────────────────────────
    s.pnlEDS = uipanel(parent, 'BorderType', 'line');
    s.pnlEDS.Layout.Row = 12;

    s.edsInnerGL = uigridlayout(s.pnlEDS, [20 2], ...
        'RowHeight', {28, 28, 100, 28, 28, 28, 28, 28, 28, 28, ...
                       28, 28, 28, 28, 28, 28, ...
                       28, 28, 28, 28}, ...
        'ColumnWidth', {'1x', '1x'}, ...
        'Padding', [4 4 18 4], ...   % right pad clears the panel scrollbar (channel-colour dropdown arrow)
        'RowSpacing', 3);

    % ── Row 1: Enter EDS Mode (full-width) ───────────────────────────────
    s.btnEnterEDS = uibutton(s.edsInnerGL, 'Text', 'Enter EDS Mode', ...
        'ButtonPushedFcn', callbacks.onEnterEDS, ...
        'BackgroundColor', BTN_PRIMARY, ...
        'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Enable', 'off', ...
        'Tooltip', 'Enter multi-channel EDS false-color composite mode');
    s.btnEnterEDS.Layout.Row = 1; s.btnEnterEDS.Layout.Column = [1 2];

    % ── Row 2: Add / Remove channel ──────────────────────────────────────
    s.btnAddChannel = uibutton(s.edsInnerGL, 'Text', 'Add Channel', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEDSListChange('add'), ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Add active image as an EDS channel');
    s.btnAddChannel.Layout.Row = 2; s.btnAddChannel.Layout.Column = 1;

    s.btnRemoveChannel = uibutton(s.edsInnerGL, 'Text', 'Remove', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEDSListChange('remove'), ...
        'BackgroundColor', BTN_DANGER, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Remove selected channel from composite');
    s.btnRemoveChannel.Layout.Row = 2; s.btnRemoveChannel.Layout.Column = 2;

    % ── Row 3: Channel list box ───────────────────────────────────────────
    s.lbEDSChannels = uilistbox(s.edsInnerGL, ...
        'Items', {'(no channels)'}, ...
        'ItemsData', 0, ...
        'ValueChangedFcn', callbacks.onEDSChannelSelected, ...
        'FontSize', 11);
    s.lbEDSChannels.Layout.Row = 3; s.lbEDSChannels.Layout.Column = [1 2];

    % ── Row 4: Color label + dropdown ────────────────────────────────────
    s.EDS_COLORS = {'red', 'green', 'blue', 'cyan', 'magenta', 'yellow', 'white'};

    lblEDSColor = uilabel(s.edsInnerGL, 'Text', 'Color:', ...
        'FontSize', 11, 'HorizontalAlignment', 'right');
    lblEDSColor.Layout.Row = 4; lblEDSColor.Layout.Column = 1;

    s.ddChannelColor = uidropdown(s.edsInnerGL, ...
        'Items', s.EDS_COLORS, ...
        'Value', 'red', ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('color'), ...
        'Enable', 'off', ...
        'Tooltip', 'Pseudo-color for this channel');
    s.ddChannelColor.Layout.Row = 4; s.ddChannelColor.Layout.Column = 2;

    % ── Row 5: Visible checkbox + intensity label ─────────────────────────
    s.cbChannelVisible = uicheckbox(s.edsInnerGL, ...
        'Text', 'Visible', ...
        'Value', true, ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('visible'), ...
        'Enable', 'off');
    s.cbChannelVisible.Layout.Row = 5; s.cbChannelVisible.Layout.Column = 1;

    s.lblEDSIntensity = uilabel(s.edsInnerGL, 'Text', 'Int: 1.00', ...
        'FontSize', 11, 'HorizontalAlignment', 'center');
    s.lblEDSIntensity.Layout.Row = 5; s.lblEDSIntensity.Layout.Column = 2;

    % ── Row 6: Intensity slider (full-width) ──────────────────────────────
    s.sldChannelIntensity = uislider(s.edsInnerGL, ...
        'Limits', [0 1], ...
        'Value', 1, ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('intensity'), ...
        'Enable', 'off');
    s.sldChannelIntensity.Layout.Row = 6; s.sldChannelIntensity.Layout.Column = [1 2];

    % ── Row 7: Channel label edit field (full-width) ──────────────────────
    s.efChannelLabel = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '', ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('label'), ...
        'Enable', 'off', ...
        'Placeholder', 'Channel label');
    s.efChannelLabel.Layout.Row = 7; s.efChannelLabel.Layout.Column = [1 2];

    % ── Row 8: Export RGB (full-width) ────────────────────────────────────
    s.btnExportComposite = uibutton(s.edsInnerGL, 'Text', 'Export RGB', ...
        'ButtonPushedFcn', callbacks.onExportEDSComposite, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Save the blended RGB composite to PNG/TIFF');
    s.btnExportComposite.Layout.Row = 8; s.btnExportComposite.Layout.Column = [1 2];

    % ── EDS Quantification controls (rows 9-16) ───────────────────────────

    % Row 9: Assign Elements (full-width)
    s.btnAssignElements = uibutton(s.edsInnerGL, 'Text', 'Assign Elements', ...
        'ButtonPushedFcn', callbacks.onAssignElements, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Assign element symbols to EDS channels');
    s.btnAssignElements.Layout.Row = 9; s.btnAssignElements.Layout.Column = [1 2];

    % Row 10: Quantify (full-width) — behaviour is driven by ddEDSMethod
    s.btnQuantifyCL = uibutton(s.edsInnerGL, 'Text', 'Quantify (Cliff-Lorimer)', ...
        'ButtonPushedFcn', callbacks.onQuantifyCL, ...
        'BackgroundColor', BTN_PRIMARY, 'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Enable', 'off', ...
        'Tooltip', 'Compute composition using the method selected below');
    s.btnQuantifyCL.Layout.Row = 10; s.btnQuantifyCL.Layout.Column = [1 2];

    % Row 11: Method label + dropdown
    lblEDSMethod = uilabel(s.edsInnerGL, 'Text', 'Method:', ...
        'FontSize', 11, 'HorizontalAlignment', 'right');
    lblEDSMethod.Layout.Row = 11; lblEDSMethod.Layout.Column = 1;

    s.ddEDSMethod = uidropdown(s.edsInnerGL, ...
        'Items', {'Window integration', 'Peak fit', [char(950) '-factor']}, ...
        'Value', 'Window integration', ...
        'Tag', 'ddEDSMethod', ...
        'Enable', 'off', ...
        'Tooltip', ['Window integration (default): per-pixel energy-window sums. ' ...
                    'Peak fit: constrained multi-Gaussian deconvolution, resolves ' ...
                    'overlapping lines (bulk, needs an EDS cube). ' char(950) ...
                    '-factor: absolute quantification with mass-thickness (needs dose).']);
    s.ddEDSMethod.Layout.Row = 11; s.ddEDSMethod.Layout.Column = 2;

    % Row 12: Remove artifacts checkbox (full-width)
    s.cbEDSRemoveArtifacts = uicheckbox(s.edsInnerGL, ...
        'Text', 'Remove escape/sum artifacts', ...
        'Value', false, ...
        'Tag', 'cbEDSRemoveArtifacts', ...
        'Enable', 'off', ...
        'Tooltip', ['Pre-pass: subtract predicted Si-escape and sum/pile-up peaks ' ...
                    '(e.g. Cu escape inflating Fe-K' char(945) ...
                    ') before quantifying. Needs an EDS cube.']);
    s.cbEDSRemoveArtifacts.Layout.Row = 12; s.cbEDSRemoveArtifacts.Layout.Column = [1 2];

    % Row 13: Map background label + dropdown
    lblEDSMapBg = uilabel(s.edsInnerGL, 'Text', 'Map BG:', ...
        'FontSize', 11, 'HorizontalAlignment', 'right');
    lblEDSMapBg.Layout.Row = 13; lblEDSMapBg.Layout.Column = 1;

    s.ddEDSMapBackground = uidropdown(s.edsInnerGL, ...
        'Items', {'none', 'linear', 'bremsstrahlung'}, ...
        'Value', 'linear', ...
        'Tag', 'ddEDSMapBackground', ...
        'Enable', 'off', ...
        'Tooltip', ['Background model for cube-derived element maps built on ' ...
                    'Enter EDS Mode. "bremsstrahlung" fits the physical Kramers ' ...
                    'continuum instead of a linear chord (needs E0 below).']);
    s.ddEDSMapBackground.Layout.Row = 13; s.ddEDSMapBackground.Layout.Column = 2;

    % Row 14: Beam energy (E0) override for the bremsstrahlung background
    lblEDSE0KeV = uilabel(s.edsInnerGL, 'Text', 'E0 (keV):', ...
        'FontSize', 11, 'HorizontalAlignment', 'right');
    lblEDSE0KeV.Layout.Row = 14; lblEDSE0KeV.Layout.Column = 1;

    s.edtEDSE0KeV = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '', ...
        'Tag', 'edtEDSE0KeV', ...
        'Enable', 'off', ...
        'Placeholder', 'auto (beam kV)');
    s.edtEDSE0KeV.Layout.Row = 14; s.edtEDSE0KeV.Layout.Column = 2;

    % Row 15: ζ-factor dose inputs (probe current + live time)
    s.edtEDSDoseCurrentNA = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '1.0', ...
        'Tag', 'edtEDSDoseCurrentNA', ...
        'Enable', 'off', ...
        'Placeholder', 'I (nA)');
    s.edtEDSDoseCurrentNA.Layout.Row = 15; s.edtEDSDoseCurrentNA.Layout.Column = 1;

    s.edtEDSDoseLiveTimeS = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '100', ...
        'Tag', 'edtEDSDoseLiveTimeS', ...
        'Enable', 'off', ...
        'Placeholder', 't (s)');
    s.edtEDSDoseLiveTimeS.Layout.Row = 15; s.edtEDSDoseLiveTimeS.Layout.Column = 2;

    % Row 16: ζ-factor absolute Si standard (full-width edit field)
    lblEDSZetaSi = uilabel(s.edsInnerGL, 'Text', [char(950) '_Si (kg/m' char(178) '):'], ...
        'FontSize', 11, 'HorizontalAlignment', 'right');
    lblEDSZetaSi.Layout.Row = 16; lblEDSZetaSi.Layout.Column = 1;

    s.edtEDSZetaSi = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '1000', ...
        'Tag', 'edtEDSZetaSi', ...
        'Enable', 'off', ...
        'Tooltip', ['Absolute ' char(950) '-factor for a Si-K' char(945) ...
                    ' standard; bootstraps every other element via the 200 kV k-table ' ...
                    '(imaging.eds.zetaFromKFactors).']);
    s.edtEDSZetaSi.Layout.Row = 16; s.edtEDSZetaSi.Layout.Column = 2;

    % Row 17: Composition Profile (full-width)
    s.btnCompositionProfile = uibutton(s.edsInnerGL, 'Text', 'Composition Profile', ...
        'ButtonPushedFcn', callbacks.onCompositionProfile, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click two points for a line composition profile');
    s.btnCompositionProfile.Layout.Row = 17; s.btnCompositionProfile.Layout.Column = [1 2];

    % Row 18: ROI Composition (full-width)
    s.btnROIComposition = uibutton(s.edsInnerGL, 'Text', 'ROI Composition', ...
        'ButtonPushedFcn', callbacks.onROIComposition, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click two corners for mean composition in ROI');
    s.btnROIComposition.Layout.Row = 18; s.btnROIComposition.Layout.Column = [1 2];

    % ── Row 19: Thickness + Take-off angle for ZAF ───────────────────────
    s.edtEDSThickness = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '100', 'Placeholder', 't (nm)');
    s.edtEDSThickness.Layout.Row = 19; s.edtEDSThickness.Layout.Column = 1;

    s.edtEDSTakeOff = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '20', 'Placeholder', 'angle (deg)');
    s.edtEDSTakeOff.Layout.Row = 19; s.edtEDSTakeOff.Layout.Column = 2;

    % ── Row 20: Quantify ZAF (full-width) ────────────────────────────────
    s.btnQuantifyZAF = uibutton(s.edsInnerGL, 'Text', 'Quantify ZAF', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'ZAF-corrected quantification (thick specimens)', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.onQuantifyZAF);
    s.btnQuantifyZAF.Layout.Row = 20; s.btnQuantifyZAF.Layout.Column = [1 2];
end
