function s = buildDiffractionPanel(parent, palette, callbacks, opts)
%BUILDDIFFRACTIONPANEL  Construct the Diffraction Indexing sub-panel.
%
% Syntax
%   s = fermiViewer.diffraction.buildDiffractionPanel(parent, palette, callbacks, opts)
%
% Extracted from FermiViewer.m (Section 9) following the buildEELSPanel
% pattern: the parent unpacks the returned handle struct back into local
% variables, so buildBigUI / setToolsEnabled keep referencing them unchanged.
%
% Inputs
%   parent     uigridlayout (toolsGL). The header button is placed at
%              opts.headerRow and the panel at opts.panelRow.
%   palette    struct of semantic button colours:
%                .primary  — green, primary actions (Match Phases)
%                .tool     — gray, secondary tools
%                .danger   — red, destructive (Clear)
%                .fg       — foreground text colour
%   callbacks  struct of function handles:
%                .onDiffractionAction — @(action) dispatcher; the ROI and
%                                       spot/match actions all route here
%                .onVirtualDarkField  — @() VDF action
%                .toggleSection       — @(sectId) collapse/expand handler
%   opts       struct:
%                .arrowShut  — collapsed-arrow glyph string for the header
%                .sectDiff   — section id passed to toggleSection
%                .headerRow  — toolsGL row for the section header (e.g. 17)
%                .panelRow   — toolsGL row for the panel (e.g. 18)
%
% Outputs
%   s   struct of widget handles. Spot/indexing widgets (unchanged from the
%       previous inline block) plus the new Analysis ROI controls:
%         .btnROIRect    — set rectangular Analysis ROI
%         .btnROICircle  — set circular Analysis ROI
%         .btnClearROI   — clear the Analysis ROI (revert to full image)
%
% Example
%   diff_ = fermiViewer.diffraction.buildDiffractionPanel(toolsGL, palette, cb, opts);
%   btnAutoDetectSpots = diff_.btnAutoDetectSpots;  % ... unpack the rest

    arguments
        parent
        palette   struct
        callbacks struct
        opts      struct
    end

    BTN_PRIMARY = palette.primary;
    BTN_TOOL    = palette.tool;
    BTN_DANGER  = palette.danger;
    BTN_FG      = palette.fg;

    onDiffractionAction = callbacks.onDiffractionAction;
    onVirtualDarkField  = callbacks.onVirtualDarkField;

    % ── Section header ───────────────────────────────────────────────────
    s.btnDiffHeader = fermiViewer.chrome.sectionHeader(parent, ...
        [opts.arrowShut ' Diffraction'], @(~,~) callbacks.toggleSection(opts.sectDiff));
    s.btnDiffHeader.Layout.Row = opts.headerRow;

    s.pnlDiff = uipanel(parent, 'BorderType', 'line');
    s.pnlDiff.Layout.Row = opts.panelRow;

    % Grid grew from 9 to 12 rows: rows 10-12 host the Analysis ROI controls.
    diffInnerGL = uigridlayout(s.pnlDiff, [12 2], ...
        'RowHeight', {28, 28, 28, 28, 28, 28, '1x', 28, 28, 22, 28, 28}, ...
        'ColumnWidth', {'1x', '1x'}, ...
        'Padding', [4 4 4 4], ...
        'RowSpacing', 3);

    s.btnAutoDetectSpots = uibutton(diffInnerGL, 'Text', 'Auto-detect Spots', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('autoDetect'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Automatically find diffraction spots');
    s.btnAutoDetectSpots.Layout.Row = 1; s.btnAutoDetectSpots.Layout.Column = 1;

    s.btnClickDiffSpot = uibutton(diffInnerGL, 'Text', 'Click Spots', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('clickSpot'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click to manually mark diffraction spots');
    s.btnClickDiffSpot.Layout.Row = 1; s.btnClickDiffSpot.Layout.Column = 2;

    s.btnClearDiffSpots = uibutton(diffInnerGL, 'Text', 'Clear Spots', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('clearSpots'), ...
        'BackgroundColor', BTN_DANGER, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Remove all diffraction spot markers');
    s.btnClearDiffSpots.Layout.Row = 2; s.btnClearDiffSpots.Layout.Column = 1;

    s.lblSpotCount = uilabel(diffInnerGL, 'Text', '0 spots', ...
        'FontSize', 11, 'HorizontalAlignment', 'center');
    s.lblSpotCount.Layout.Row = 2; s.lblSpotCount.Layout.Column = 2;

    s.lblCameraLen = uilabel(diffInnerGL, 'Text', 'Camera Length (mm):', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    s.lblCameraLen.Layout.Row = 3; s.lblCameraLen.Layout.Column = 1;

    s.edtCameraLen = uieditfield(diffInnerGL, 'text', ...
        'Value', '', 'Placeholder', 'e.g. 200', 'FontSize', 11);
    s.edtCameraLen.Layout.Row = 3; s.edtCameraLen.Layout.Column = 2;

    s.lblAccVoltage = uilabel(diffInnerGL, 'Text', 'Voltage (kV):', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    s.lblAccVoltage.Layout.Row = 4; s.lblAccVoltage.Layout.Column = 1;

    s.ddAccVoltage = uidropdown(diffInnerGL, ...
        'Items', {'80 kV', '100 kV', '120 kV', '200 kV', '300 kV'}, ...
        'Value', '200 kV', ...
        'Enable', 'off', ...
        'Tooltip', 'Electron accelerating voltage');
    s.ddAccVoltage.Layout.Row = 4; s.ddAccVoltage.Layout.Column = 2;

    s.btnMatchDiffraction = uibutton(diffInnerGL, 'Text', 'Match Phases', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('match'), ...
        'BackgroundColor', BTN_PRIMARY, 'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Enable', 'off', ...
        'Tooltip', 'Index diffraction pattern and match to crystal phases');
    s.btnMatchDiffraction.Layout.Row = 5; s.btnMatchDiffraction.Layout.Column = 1;

    s.btnOverlayDiffRings = uibutton(diffInnerGL, 'Text', 'Overlay Rings', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('overlayRings'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Overlay d-spacing rings for selected phase');
    s.btnOverlayDiffRings.Layout.Row = 5; s.btnOverlayDiffRings.Layout.Column = 2;

    s.lblZoneAxisLabel = uilabel(diffInnerGL, 'Text', 'Zone Axis:', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    s.lblZoneAxisLabel.Layout.Row = 6; s.lblZoneAxisLabel.Layout.Column = 1;

    s.lblZoneAxis = uilabel(diffInnerGL, 'Text', '', ...
        'FontSize', 11, 'HorizontalAlignment', 'left', 'FontWeight', 'bold');
    s.lblZoneAxis.Layout.Row = 6; s.lblZoneAxis.Layout.Column = 2;

    s.lbxDiffResults = uilistbox(diffInnerGL, ...
        'Items', {}, ...
        'FontSize', 11);
    s.lbxDiffResults.Layout.Row = 7; s.lbxDiffResults.Layout.Column = [1 2];

    % Row 8: Zone axis + Simulate
    s.edtZoneAxis = uieditfield(diffInnerGL, 'text', ...
        'Value', '0 0 1', 'Placeholder', 'Zone axis [u v w]');
    s.edtZoneAxis.Layout.Row = 8; s.edtZoneAxis.Layout.Column = 1;

    s.btnSimDiffraction = uibutton(diffInnerGL, 'Text', 'Simulate', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Kinematic diffraction simulation', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('simulate'));
    s.btnSimDiffraction.Layout.Row = 8; s.btnSimDiffraction.Layout.Column = 2;

    % Row 9: Virtual Dark-Field
    s.btnVDF = uibutton(diffInnerGL, 'Text', 'Virtual Dark-Field', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Select FFT spot for virtual dark-field image', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', @(~,~) onVirtualDarkField());
    s.btnVDF.Layout.Row = 9; s.btnVDF.Layout.Column = [1 2];

    % ── Rows 10-12: Analysis ROI ──────────────────────────────────────────
    % Restricts FFT / diffraction (spot detect + index) / CTF / defect count
    % to a drawn rectangle or circle. See fermiViewer.analysis.analysisRegion.
    s.lblAnalysisROI = uilabel(diffInnerGL, 'Text', 'Analysis ROI (FFT / diffraction):', ...
        'FontSize', 10, 'HorizontalAlignment', 'left', 'FontAngle', 'italic');
    s.lblAnalysisROI.Layout.Row = 10; s.lblAnalysisROI.Layout.Column = [1 2];

    s.btnROIRect = uibutton(diffInnerGL, 'Text', 'ROI Rect', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('setAnalysisROIRect'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Draw a rectangular region; FFT/diffraction then use only that region');
    s.btnROIRect.Layout.Row = 11; s.btnROIRect.Layout.Column = 1;

    s.btnROICircle = uibutton(diffInnerGL, 'Text', 'ROI Circle', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('setAnalysisROICircle'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Draw a circular region (center + edge); FFT/diffraction then use only that region');
    s.btnROICircle.Layout.Row = 11; s.btnROICircle.Layout.Column = 2;

    s.btnClearROI = uibutton(diffInnerGL, 'Text', 'Clear ROI', ...
        'ButtonPushedFcn', @(~,~) onDiffractionAction('clearAnalysisROI'), ...
        'BackgroundColor', BTN_DANGER, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Clear the Analysis ROI — FFT/diffraction revert to the full image');
    s.btnClearROI.Layout.Row = 12; s.btnClearROI.Layout.Column = [1 2];
end
