function s = buildEELSPanel(parent, tk, palette, callbacks)
%BUILDEELSPANEL  Construct the EELS Spectrum sub-panel for FermiViewer.
%
% Syntax
%   s = fermiViewer.eels.buildEELSPanel(parent, tk, palette, callbacks)
%
% Inputs
%   parent     uigridlayout (eelsInnerGL parent — pnlEELS is created here)
%              This is the toolsGL grid; the function creates pnlEELS and
%              sets its Layout.Row = 16.
%   tk         UX tokens struct (unused here, reserved for future theming)
%   palette    struct of semantic button colours:
%                .primary  — green, primary actions
%                .tool     — gray, secondary tools
%                .fg       — white foreground text
%   callbacks  struct of function handles:
%                .onEnterEELS          — Enter/Exit EELS mode toggle
%                .onEELSAction         — dispatches 'bgFit', 'showEdges',
%                                        'extractMap', 'thicknessMap',
%                                        'alignZLP'
%                .onEELSAdvanced       — dispatches 'deconvolve',
%                                        'fourierRatio', 'richardsonLucy',
%                                        'elnes', 'kramersKronig', 'svd'
%                .onEELSNavigateToggle — state-button toggle for pixel nav
%
% Outputs
%   s   struct of widget handles for all 21 interactive widgets:
%         .pnlEELS             — the outer uipanel (parented to toolsGL)
%         .btnEnterEELS        — Enter/Exit EELS mode button
%         .edtEELSPreEdgeStart — pre-edge window start edit field
%         .edtEELSPreEdgeEnd   — pre-edge window end edit field
%         .btnEELSFitBG        — Fit Background button
%         .ddEELSMethod        — background model dropdown
%         .chkShowEdges        — Show Edges checkbox
%         .ddEdgeFilter        — element filter dropdown
%         .edtEELSSignalStart  — signal window start edit field
%         .edtEELSSignalEnd    — signal window end edit field
%         .btnEELSExtractMap   — Extract Map button
%         .btnEELSThickness    — Thickness Map button
%         .btnEELSAlignZLP     — Align ZLP button
%         .btnEELSDeconvolve   — Deconvolve (Fourier-Log) button
%         .btnEELSFourierRatio — Fourier-ratio deconvolution button (needs
%                                a second, low-loss spectrum as PSF)
%         .btnEELSRichLucy     — Richardson-Lucy deconvolution button
%                                (sharpens using the ZLP as PSF)
%         .btnEELSELNES        — ELNES extraction button
%         .edtEELSEdgeOnset    — edge onset energy edit field
%         .btnEELSKK           — Kramers-Kronig button
%         .btnEELSNavigate     — Navigate Pixel state button
%         .btnEELSSVD          — SVD Decompose button
%
% Examples
%   eels_ = fermiViewer.eels.buildEELSPanel(toolsGL, tk, palette, callbacks);
%   eels_.pnlEELS.Layout.Row = 16;
%   btnEnterEELS = eels_.btnEnterEELS;

    arguments
        parent
        tk         struct  %#ok<INUSA>  % reserved for future theming
        palette    struct
        callbacks  struct
    end

    % Palette shorthands
    BTN_PRIMARY = palette.primary;
    BTN_TOOL    = palette.tool;
    BTN_FG      = palette.fg;

    % ── Outer panel (parented to toolsGL, row 16) ────────────────────────
    s.pnlEELS = uipanel(parent, 'BorderType', 'line');
    s.pnlEELS.Layout.Row = 16;

    % RowHeight must have one entry per row (13). A missing entry would make
    % that row default to '1x', stretching its widgets to fill all leftover
    % height (see the SVD Decompose regression this comment used to warn
    % about, back when the grid had only 12 rows).
    eelsInnerGL = uigridlayout(s.pnlEELS, [13 2], ...
        'RowHeight', {28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28}, ...
        'ColumnWidth', {'1x', '1x'}, ...
        'Padding', [4 4 4 4], ...
        'RowSpacing', 3);

    % ── Row 1: Enter EELS (full-width) ───────────────────────────────────
    s.btnEnterEELS = uibutton(eelsInnerGL, 'Text', 'Enter EELS', ...
        'ButtonPushedFcn', callbacks.onEnterEELS, ...
        'BackgroundColor', BTN_PRIMARY, ...
        'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Enable', 'off', ...
        'Tooltip', 'Enter EELS spectrum analysis mode');
    s.btnEnterEELS.Layout.Row = 1; s.btnEnterEELS.Layout.Column = [1 2];

    % ── Row 2: Pre-edge Window ────────────────────────────────────────────
    lblEELSPreEdge = uilabel(eelsInnerGL, 'Text', 'Pre-edge Window:', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    lblEELSPreEdge.Layout.Row = 2; lblEELSPreEdge.Layout.Column = 1;

    eelsPreEdgeGL = uigridlayout(eelsInnerGL, [1 2], ...
        'RowHeight', {'1x'}, 'ColumnWidth', {'1x','1x'}, ...
        'Padding', [0 0 0 0], 'RowSpacing', 0, 'ColumnSpacing', 2);
    eelsPreEdgeGL.Layout.Row = 2; eelsPreEdgeGL.Layout.Column = 2;

    s.edtEELSPreEdgeStart = uieditfield(eelsPreEdgeGL, 'text', ...
        'Value', '100', 'Placeholder', 'E1 eV', 'FontSize', 11);
    s.edtEELSPreEdgeStart.Layout.Row = 1; s.edtEELSPreEdgeStart.Layout.Column = 1;

    s.edtEELSPreEdgeEnd = uieditfield(eelsPreEdgeGL, 'text', ...
        'Value', '700', 'Placeholder', 'E2 eV', 'FontSize', 11);
    s.edtEELSPreEdgeEnd.Layout.Row = 1; s.edtEELSPreEdgeEnd.Layout.Column = 2;

    % ── Row 3: Fit Background + method dropdown ───────────────────────────
    s.btnEELSFitBG = uibutton(eelsInnerGL, 'Text', 'Fit Background', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAction('bgFit'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Fit and subtract pre-edge background');
    s.btnEELSFitBG.Layout.Row = 3; s.btnEELSFitBG.Layout.Column = 1;

    s.ddEELSMethod = uidropdown(eelsInnerGL, ...
        'Items', {'powerlaw', 'exponential'}, ...
        'Value', 'powerlaw', ...
        'Enable', 'off', ...
        'Tooltip', 'Background fitting model');
    s.ddEELSMethod.Layout.Row = 3; s.ddEELSMethod.Layout.Column = 2;

    % ── Row 4: Show Edges checkbox + element filter ───────────────────────
    s.chkShowEdges = uicheckbox(eelsInnerGL, 'Text', 'Show Edges', ...
        'Value', false, ...
        'ValueChangedFcn', @(~,~) callbacks.onEELSAction('showEdges'), ...
        'Enable', 'off');
    s.chkShowEdges.Layout.Row = 4; s.chkShowEdges.Layout.Column = 1;

    s.ddEdgeFilter = uidropdown(eelsInnerGL, ...
        'Items', {'All'}, ...
        'Value', 'All', ...
        'Enable', 'off', ...
        'Tooltip', 'Filter edges by element');
    s.ddEdgeFilter.Layout.Row = 4; s.ddEdgeFilter.Layout.Column = 2;

    % ── Row 5: Signal Window ──────────────────────────────────────────────
    lblEELSSigWin = uilabel(eelsInnerGL, 'Text', 'Signal Window:', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    lblEELSSigWin.Layout.Row = 5; lblEELSSigWin.Layout.Column = 1;

    eelsSigWinGL = uigridlayout(eelsInnerGL, [1 2], ...
        'RowHeight', {'1x'}, 'ColumnWidth', {'1x','1x'}, ...
        'Padding', [0 0 0 0], 'RowSpacing', 0, 'ColumnSpacing', 2);
    eelsSigWinGL.Layout.Row = 5; eelsSigWinGL.Layout.Column = 2;

    s.edtEELSSignalStart = uieditfield(eelsSigWinGL, 'text', ...
        'Value', '700', 'Placeholder', 'E1 eV', 'FontSize', 11);
    s.edtEELSSignalStart.Layout.Row = 1; s.edtEELSSignalStart.Layout.Column = 1;

    s.edtEELSSignalEnd = uieditfield(eelsSigWinGL, 'text', ...
        'Value', '750', 'Placeholder', 'E2 eV', 'FontSize', 11);
    s.edtEELSSignalEnd.Layout.Row = 1; s.edtEELSSignalEnd.Layout.Column = 2;

    % ── Row 6: Extract Map + Thickness Map ───────────────────────────────
    s.btnEELSExtractMap = uibutton(eelsInnerGL, 'Text', 'Extract Map', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAction('extractMap'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Extract EELS elemental map from spectrum image');
    s.btnEELSExtractMap.Layout.Row = 6; s.btnEELSExtractMap.Layout.Column = 1;

    s.btnEELSThickness = uibutton(eelsInnerGL, 'Text', 'Thickness Map', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAction('thicknessMap'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Compute t/lambda thickness map from log-ratio');
    s.btnEELSThickness.Layout.Row = 6; s.btnEELSThickness.Layout.Column = 2;

    % ── Row 7: Align ZLP (full-width) ────────────────────────────────────
    s.btnEELSAlignZLP = uibutton(eelsInnerGL, 'Text', 'Align ZLP', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAction('alignZLP'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Align zero-loss peak across spectrum image frames');
    s.btnEELSAlignZLP.Layout.Row = 7; s.btnEELSAlignZLP.Layout.Column = [1 2];

    % ── Row 8: Deconvolve — Fourier-Log (full-width) ─────────────────────
    s.btnEELSDeconvolve = uibutton(eelsInnerGL, 'Text', 'Deconvolve', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Fourier-log plural scattering removal', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAdvanced('deconvolve'));
    s.btnEELSDeconvolve.Layout.Row = 8; s.btnEELSDeconvolve.Layout.Column = [1 2];

    % ── Row 9: Fourier Ratio + Rich-Lucy (paired, half-width each) ────────
    % Same row/half-width pairing as Extract Map + Thickness Map (row 6);
    % both labels are within the length already proven to fit that column
    % width ("Thickness Map" is 13 chars, "Fourier Ratio" is also 13).
    %
    % Enable is hardcoded 'on' rather than 'off' (unlike every sibling
    % button in this panel): the on-load/on-clear graying for the rest of
    % the panel is driven by fermiViewer.setToolsEnabled.m explicitly
    % enumerating each button by name, which is wired from FermiViewer.m
    % local variables that are out of scope to add here (FermiViewer.m is
    % not to be edited for this feature). This is safe because both
    % These two start disabled like every sibling, but they are NOT in the
    % FermiViewer.m closure list that setToolsEnabled drives (adding them
    % there costs monolith lines the size ratchet has no room for). Instead
    % they carry Tag EELS_EXTRA_TAG and +eels/dispatch.m toggles them by tag
    % on enter/exit, reaching them via ancestor(ctx.btnEnterEELS,'figure').
    % Keep the tag in sync with the toggleTaggedButtons helper in dispatch.m.
    s.btnEELSFourierRatio = uibutton(eelsInnerGL, 'Text', 'Fourier Ratio', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Fourier-ratio plural scattering removal (needs a low-loss spectrum as PSF)', ...
        'Enable', 'off', 'Tag', 'eelsExtraDeconvBtn', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAdvanced('fourierRatio'));
    s.btnEELSFourierRatio.Layout.Row = 9; s.btnEELSFourierRatio.Layout.Column = 1;

    s.btnEELSRichLucy = uibutton(eelsInnerGL, 'Text', 'Rich-Lucy', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Richardson-Lucy deconvolution using the ZLP as PSF', ...
        'Enable', 'off', 'Tag', 'eelsExtraDeconvBtn', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAdvanced('richardsonLucy'));
    s.btnEELSRichLucy.Layout.Row = 9; s.btnEELSRichLucy.Layout.Column = 2;

    % ── Row 10: ELNES + edge onset ─────────────────────────────────────────
    s.btnEELSELNES = uibutton(eelsInnerGL, 'Text', 'ELNES', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Extract near-edge fine structure', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAdvanced('elnes'));
    s.btnEELSELNES.Layout.Row = 10; s.btnEELSELNES.Layout.Column = 1;

    s.edtEELSEdgeOnset = uieditfield(eelsInnerGL, 'text', ...
        'Value', '708', 'Placeholder', 'Onset eV', ...
        'Tooltip', 'Edge onset energy for ELNES');
    s.edtEELSEdgeOnset.Layout.Row = 10; s.edtEELSEdgeOnset.Layout.Column = 2;

    % ── Row 11: Kramers-Kronig (full-width) ──────────────────────────────
    s.btnEELSKK = uibutton(eelsInnerGL, 'Text', 'Kramers-Kronig', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Compute dielectric function from low-loss EELS', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAdvanced('kramersKronig'));
    s.btnEELSKK.Layout.Row = 11; s.btnEELSKK.Layout.Column = [1 2];

    % ── Row 12: Navigate Pixel — state button (full-width) ───────────────
    s.btnEELSNavigate = uibutton(eelsInnerGL, 'state', 'Text', 'Navigate Pixel', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Click on image to show pixel spectrum', ...
        'Enable', 'off', ...
        'ValueChangedFcn', callbacks.onEELSNavigateToggle);
    s.btnEELSNavigate.Layout.Row = 12; s.btnEELSNavigate.Layout.Column = [1 2];

    % ── Row 13: SVD / MSA decomposition (full-width) ─────────────────────
    s.btnEELSSVD = uibutton(eelsInnerGL, 'Text', 'SVD Decompose', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'Multivariate decomposition of spectrum image (eigenspectra + score maps)', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEELSAdvanced('svd'));
    s.btnEELSSVD.Layout.Row = 13; s.btnEELSSVD.Layout.Column = [1 2];
end
