function s = buildAnnotationsPanel(parent, tk, palette, callbacks)
%BUILDANNOTATIONSPANEL  Construct the Annotations sub-panel for FermiViewer.
%
% Syntax
%   s = emViewer.buildAnnotationsPanel(parent, tk, palette, callbacks)
%
% Inputs
%   parent     uigridlayout (toolsGL) — the function creates pnlAnnot and
%              sets its Layout.Row = 10.
%   tk         UX tokens struct (unused here, reserved for future theming)
%   palette    struct of semantic button colours:
%                .tool    — gray, secondary tools
%                .danger  — red, destructive actions
%                .fg      — white foreground text
%                .overlayColor — [R G B] colour for cyan overlay / 'Cyan' swatch
%   callbacks  struct of function handles:
%                .onAnnotationAction — dispatches 'place', 'clear', 'undoLast'
%                .onPlaceArrow       — draw arrow annotation
%                .onPlaceLine        — draw line annotation
%                .onPlaceRect        — draw rectangle annotation
%                .onPlaceCircle      — draw circle annotation
%
% Outputs
%   s   struct of widget handles for all interactive widgets:
%         .pnlAnnot       — outer uipanel (parented to toolsGL, row 10)
%         .efAnnotText    — text input edit field
%         .spnAnnotFont   — font size spinner
%         .ddAnnotColor   — colour selection dropdown
%         .btnPlaceAnnot  — Place Text button
%         .btnClearAnnot  — Clear All button
%         .btnPlaceArrow  — Arrow shape button
%         .btnPlaceLine   — Line shape button
%         .btnPlaceRect   — Rect shape button
%         .btnPlaceCircle — Circle shape button
%         .btnUndoAnnot   — Undo Last button
%
% Examples
%   annot_ = emViewer.buildAnnotationsPanel(toolsGL, tk, palette, callbacks);
%   btnPlaceAnnot = annot_.btnPlaceAnnot;

    arguments
        parent
        tk         struct  %#ok<INUSA>  % reserved for future theming
        palette    struct
        callbacks  struct
    end

    % Palette shorthands
    BTN_TOOL    = palette.tool;
    BTN_DANGER  = palette.danger;
    BTN_FG      = palette.fg;
    OVERLAY_CLR = palette.overlayColor;

    % ── Outer panel (parented to toolsGL, row 10) ────────────────────────
    s.pnlAnnot = uipanel(parent, 'BorderType', 'line');
    s.pnlAnnot.Layout.Row = 10;

    s.annotInnerGL = uigridlayout(s.pnlAnnot, [7 2], ...
        'RowHeight',     {20, 20, 20, 20, 20, 20, 20}, ...
        'ColumnWidth',   {'1x', '1x'}, ...
        'Padding',       [3 2 3 2], ...
        'RowSpacing',    2, ...
        'ColumnSpacing', 3);

    % ── Row 1: Text input field (spans both columns) ─────────────────────
    s.efAnnotText = uieditfield(s.annotInnerGL, 'text', ...
        'Value',   'Label', ...
        'Tooltip', 'Text to place on the image');
    s.efAnnotText.Layout.Row = 1; s.efAnnotText.Layout.Column = [1 2];

    % ── Row 2: Font size spinner + colour dropdown ────────────────────────
    s.spnAnnotFont = uispinner(s.annotInnerGL, ...
        'Value', 18, 'Limits', [6 72], 'Step', 1, ...
        'Tooltip', 'Font size for annotation text');
    s.spnAnnotFont.Layout.Row = 2; s.spnAnnotFont.Layout.Column = 1;

    % Colour dropdown — prefixed with Unicode filled square (U+25A0) as a
    % visual swatch; FontColor is updated on change so the displayed item
    % is rendered in the selected colour.
    sq = char(9632);   % ■ Unicode filled square
    s.ddAnnotColor = uidropdown(s.annotInnerGL, ...
        'Items',     {[sq ' White'], [sq ' Cyan'], [sq ' Yellow'], ...
                      [sq ' Red'],   [sq ' Black']}, ...
        'ItemsData', {'White', 'Cyan', 'Yellow', 'Red', 'Black'}, ...
        'Value',           'White', ...
        'ValueChangedFcn', @onAnnotColorChange, ...
        'BackgroundColor', [0.25 0.25 0.25], ...
        'FontColor',       [1 1 1], ...
        'Enable',  'off', ...
        'Tooltip', 'Text colour: White / Cyan / Yellow / Red / Black');
    s.ddAnnotColor.Layout.Row = 2; s.ddAnnotColor.Layout.Column = 2;

    % ── Row 3: Place Text button ──────────────────────────────────────────
    s.btnPlaceAnnot = uibutton(s.annotInnerGL, 'Text', 'Place Text', ...
        'ButtonPushedFcn', @(~,~) callbacks.onAnnotationAction('place'), ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click on image to place text annotation (Esc to cancel)');
    s.btnPlaceAnnot.Layout.Row = 3; s.btnPlaceAnnot.Layout.Column = [1 2];

    % ── Row 4: Clear All button ───────────────────────────────────────────
    s.btnClearAnnot = uibutton(s.annotInnerGL, 'Text', 'Clear All', ...
        'ButtonPushedFcn', @(~,~) callbacks.onAnnotationAction('clear'), ...
        'BackgroundColor', BTN_DANGER, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Remove all annotations from the image');
    s.btnClearAnnot.Layout.Row = 4; s.btnClearAnnot.Layout.Column = [1 2];

    % ── Row 5: Arrow / Line shape annotations ────────────────────────────
    s.btnPlaceArrow = uibutton(s.annotInnerGL, 'Text', 'Arrow', ...
        'ButtonPushedFcn', callbacks.onPlaceArrow, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click start then end to draw an arrow annotation');
    s.btnPlaceArrow.Layout.Row = 5; s.btnPlaceArrow.Layout.Column = 1;

    s.btnPlaceLine = uibutton(s.annotInnerGL, 'Text', 'Line', ...
        'ButtonPushedFcn', callbacks.onPlaceLine, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click two points to draw a line annotation');
    s.btnPlaceLine.Layout.Row = 5; s.btnPlaceLine.Layout.Column = 2;

    % ── Row 6: Rect / Circle shape annotations ───────────────────────────
    s.btnPlaceRect = uibutton(s.annotInnerGL, 'Text', 'Rect', ...
        'ButtonPushedFcn', callbacks.onPlaceRect, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click two corners to draw a rectangle annotation');
    s.btnPlaceRect.Layout.Row = 6; s.btnPlaceRect.Layout.Column = 1;

    s.btnPlaceCircle = uibutton(s.annotInnerGL, 'Text', 'Circle', ...
        'ButtonPushedFcn', callbacks.onPlaceCircle, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click center then edge to draw a circle annotation');
    s.btnPlaceCircle.Layout.Row = 6; s.btnPlaceCircle.Layout.Column = 2;

    % ── Row 7: Undo Last annotation ──────────────────────────────────────
    s.btnUndoAnnot = uibutton(s.annotInnerGL, 'Text', 'Undo Last', ...
        'ButtonPushedFcn', @(~,~) callbacks.onAnnotationAction('undoLast'), ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Remove the most recently placed annotation (Delete key)');
    s.btnUndoAnnot.Layout.Row = 7; s.btnUndoAnnot.Layout.Column = [1 2];

    % ── Colour-change callback (self-contained — updates swatch display) ──
    function onAnnotColorChange(src, ~)
        % Updates ddAnnotColor FontColor/BackgroundColor to match selection
        % and invokes palette.onAnnotColorChange if provided by the caller.
        names  = {'White', 'Cyan', 'Yellow', 'Red', 'Black'};
        colors = {[1 1 1], OVERLAY_CLR, [1 1 0], [1 0 0], [0 0 0]};
        bgs    = {[0.25 0.25 0.25], [0.15 0.15 0.15], [0.15 0.15 0.15], ...
                  [0.15 0.15 0.15], [0.85 0.85 0.85]};

        idx = find(strcmp(names, src.Value), 1);
        if isempty(idx), idx = 1; end

        src.FontColor       = colors{idx};
        src.BackgroundColor = bgs{idx};

        if isfield(callbacks, 'onAnnotColorChange')
            callbacks.onAnnotColorChange(src.Value, colors{idx});
        end
    end

end
