function s = buildToolbar(parent, ~, palette, callbacks)
%BUILDTOOLBAR  Construct the main toolbar row for FermiViewer.
%
% Syntax
%   s = emViewer.buildToolbar(parent, [], palette, callbacks)
%
% Inputs
%   parent    — uigridlayout that owns row 1 (the toolbar row)
%   ~         — reserved (uxTokens for future icon tinting; pass [])
%   palette   — struct from styles.buttonPalette() with fields:
%                 .primary, .danger, .tool, .fg
%   callbacks — struct of nested-function handles:
%                 .onOpenFiles, .onRecentFileSelected, .onRemoveImage,
%                 .onZoomFit, .onZoomActual, .onZoomOut, .onCompareToggle,
%                 .onThumbnailGrid, .onEDSToolbarToggle, .onPreferences,
%                 .onThemeToggle, .onShowEMShortcuts
%
% Outputs
%   s — struct with fields:
%         .toolbarGL      — the toolbar uigridlayout (1×13)
%         .lblFilename    — uilabel showing the current filename
%         .ddRecent       — uidropdown of recent files
%         .btnCompare     — state button for Compare mode
%         .btnGrid        — button for thumbnail grid (enabled when ≥2 images)
%         .btnEDSToolbar  — state button for EDS composite mode
%
% Notes
%   The zoom-out button uses an icon from icons/fermiviewer/zoomOut.png.
%   If the file is missing the button still renders with empty text (no error).
%   btnShortcuts is intentionally not stored in s — it has no downstream
%   enable/disable logic.

    BTN_PRIMARY = palette.primary;
    BTN_DANGER  = palette.danger;
    BTN_TOOL    = palette.tool;
    BTN_FG      = palette.fg;

    % ── Icon path ──────────────────────────────────────────────────────────
    % +emViewer is one level below the toolbox root, so go up two levels.
    iconDir   = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
                         'icons', 'fermiviewer');
    zoomIcon  = fullfile(iconDir, 'zoomOut.png');

    % ── Toolbar grid ───────────────────────────────────────────────────────
    % 13 columns — layout mirrors the original FermiViewer toolbar:
    %   1(80)   Open
    %   2(120)  Recent drop-down
    %   3(55)   Remove
    %   4(35)   Fit
    %   5(35)   1:1
    %   6(28)   Zoom out icon
    %   7(60)   Compare (state)
    %   8(35)   Grid
    %   9(35)   EDS (state)
    %   10(32)  Prefs (gear)
    %   11(32)  Theme toggle
    %   12(28)  Shortcuts (?)
    %   13(1x)  Filename label
    toolbarGL = uigridlayout(parent, [1 13], ...
        'ColumnWidth', {80, 120, 55, 35, 35, 28, 60, 35, 35, 32, 32, 28, '1x'}, ...
        'RowHeight',   {'1x'}, ...
        'Padding',     [4 2 4 2], ...
        'ColumnSpacing', 6);
    toolbarGL.Layout.Row    = 1;
    toolbarGL.Layout.Column = 1;

    % ── Widgets ────────────────────────────────────────────────────────────
    btnOpen = uibutton(toolbarGL, 'Text', 'Open', ...
        'ButtonPushedFcn', callbacks.onOpenFiles, ...
        'BackgroundColor', BTN_PRIMARY, ...
        'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Tooltip', 'Browse for TIFF or RAW image files to load');
    btnOpen.Layout.Row = 1; btnOpen.Layout.Column = 1;
    ddRecent = uidropdown(toolbarGL, ...
        'Items', {'(recent files)'}, ...
        'Value', '(recent files)', ...
        'ValueChangedFcn', callbacks.onRecentFileSelected, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Open a recently loaded file');
    ddRecent.Layout.Row = 1; ddRecent.Layout.Column = 2;

    btnRemove = uibutton(toolbarGL, 'Text', 'Remove', ...
        'ButtonPushedFcn', callbacks.onRemoveImage, ...
        'BackgroundColor', BTN_DANGER, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Remove the selected image(s) from the list');
    btnRemove.Layout.Row = 1; btnRemove.Layout.Column = 3;
    btnZoomFit = uibutton(toolbarGL, 'Text', 'Fit', ...
        'ButtonPushedFcn', callbacks.onZoomFit, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Zoom to fit the entire image in the axes');
    btnZoomFit.Layout.Row = 1; btnZoomFit.Layout.Column = 4;
    btnZoomActual = uibutton(toolbarGL, 'Text', '1:1', ...
        'ButtonPushedFcn', callbacks.onZoomActual, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Zoom to actual pixels (100% — one image pixel = one screen pixel)');
    btnZoomActual.Layout.Row = 1; btnZoomActual.Layout.Column = 5;
    btnZoomOut = uibutton(toolbarGL, 'Text', '', ...
        'Icon', zoomIcon, ...
        'ButtonPushedFcn', callbacks.onZoomOut, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Zoom out (2×)');
    btnZoomOut.Layout.Row = 1; btnZoomOut.Layout.Column = 6;
    btnCompare = uibutton(toolbarGL, 'state', 'Text', 'Compare', ...
        'ValueChangedFcn', callbacks.onCompareToggle, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Side-by-side comparison (Tab to switch active panel, arrows to scroll)');
    btnCompare.Layout.Row = 1; btnCompare.Layout.Column = 7;

    btnGrid = uibutton(toolbarGL, 'Text', 'Grid', ...
        'ButtonPushedFcn', callbacks.onThumbnailGrid, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Show thumbnail grid of all loaded images');
    btnGrid.Layout.Row = 1; btnGrid.Layout.Column = 8;

    btnEDSToolbar = uibutton(toolbarGL, 'state', 'Text', 'EDS', ...
        'ValueChangedFcn', callbacks.onEDSToolbarToggle, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Enter/exit multi-channel EDS false-color composite mode');
    btnEDSToolbar.Layout.Row = 1; btnEDSToolbar.Layout.Column = 9;

    btnPrefs = uibutton(toolbarGL, 'Text', char(9881), ...
        'ButtonPushedFcn', callbacks.onPreferences, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Preferences — default colormap, percentiles, export settings');
    btnPrefs.Layout.Row = 1; btnPrefs.Layout.Column = 10;
    btnThemeToggle = uibutton(toolbarGL, 'Text', char(9790), ...
        'ButtonPushedFcn', callbacks.onThemeToggle, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Toggle dark / light mode');
    btnThemeToggle.Layout.Row = 1; btnThemeToggle.Layout.Column = 11;
    btnShortcuts = uibutton(toolbarGL, 'Text', '?', ...
        'ButtonPushedFcn', @(~,~) callbacks.onShowEMShortcuts(), ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Tooltip', 'Keyboard shortcuts');
    btnShortcuts.Layout.Row = 1; btnShortcuts.Layout.Column = 12;
    lblFilename = uilabel(toolbarGL, 'Text', '(no image loaded)', ...
        'FontSize', 11, ...
        'FontColor', [0.85 0.85 0.85], ...
        'HorizontalAlignment', 'left');
    lblFilename.Layout.Row = 1; lblFilename.Layout.Column = 13;

    % ── Output struct ──────────────────────────────────────────────────────
    s = struct( ...
        'toolbarGL',     toolbarGL, ...
        'lblFilename',   lblFilename, ...
        'ddRecent',      ddRecent, ...
        'btnCompare',    btnCompare, ...
        'btnGrid',       btnGrid, ...
        'btnEDSToolbar', btnEDSToolbar);
end
