function s = buildMeasurementPanel(parent, palette, callbacks)
%BUILDMEASUREMENTPANEL  Build the Measurement panel widget tree for FermiViewer.
%
% Syntax
%   s = emViewer.buildMeasurementPanel(parent, palette, callbacks)
%
% Inputs
%   parent    — uipanel that hosts the inner grid (pnlMeasure)
%   palette   — struct of button colour tokens:
%                 .tool    (BTN_TOOL)
%                 .fg      (BTN_FG)
%                 .export  (BTN_EXPORT)
%                 .danger  (BTN_DANGER)
%   callbacks — struct of nested-function handles from FermiViewer.m:
%                 .onScaleBarToggle, .onScaleBarColorChange,
%                 .onScaleBarFontChange, .onLineProfile, .onBoxProfile,
%                 .onDistance, .onExportAction, .onAngleAction,
%                 .onClearOverlays, .onRemoveSelected,
%                 .onDiffractionAction, .onROIManager, .onCalibrateBar,
%                 .onDiffractionDSpacing, .onDrawROI, .onInvertImage,
%                 .onMeasurementStats, .onBatchMeasurement,
%                 .onExportProfileToDP, .panelApplyLabelFont,
%                 .panelApplySymbol, .panelApplyColor
%
% Outputs
%   s — struct of all widget handles needed by FermiViewer.m closures:
%         .measureInnerGL, .cbScaleBar, .ddScaleBarColor,
%         .spnScaleBarFont, .efScaleBarLen, .ddScaleBarUnit,
%         .btnLineProfile, .btnBoxProfile, .btnDistance,
%         .btnExportProfile, .btnAngle, .btnClearOverlays,
%         .btnRemoveMeas, .cbTiltCorrect, .spnTiltAngle,
%         .ddTiltGeometry, .btnExportMeasure, .btnDiffRings,
%         .btnROIManager, .btnCalibrateBar, .btnDSpacing,
%         .spnProfileWidth, .ddROIShape, .btnDrawROI,
%         .btnInvertImg, .btnMeasStats, .btnBatchMeas,
%         .btnExportToDP, .lblMeasLabelFont, .spnMeasLabelFont,
%         .lblMeasSymbol, .ddMeasSymbol, .lblMeasColor, .ddMeasColor
%
% Examples
%   s = emViewer.buildMeasurementPanel(pnlMeasure, palette, measCb_);

% ════════════════════════════════════════════════════════════════════════

    % ── Inner 22-row grid ────────────────────────────────────────────────
    % Row layout:
    %  1: Scale bar checkbox (span 2)
    %  2: Scale bar color dropdown + font size spinner
    %  3: Explicit length edit + unit dropdown
    %  4: Line Profile + Box Profile buttons
    %  5: Distance + Angle buttons
    %  6: (2-px spacer)
    %  7: Export CSV button (span 2)
    %  8: Clear All + Remove buttons
    %  9: Tilt correction checkbox + angle spinner
    % 10: Tilt geometry dropdown (span 2)
    % 11: Export Table + Diff Rings buttons
    % 12: ROI Manager button (span 2)
    % 13: Calibrate Bar button (span 2)
    % 14: d-Spacing + Profile width spinner
    % 15: ROI shape dropdown + Draw ROI button
    % 16: Invert Image button (span 2)
    % 17: (2-px spacer)
    % 18: Meas Stats + Batch Meas buttons
    % 19: Profile → BosonPlotter button (span 2)
    % 20: Label font label + spinner
    % 21: End symbol label + dropdown
    % 22: Line color label + dropdown

    measureInnerGL = uigridlayout(parent, [22 2], ...
        'RowHeight',   {18, 20, 22, 20, 20,  2, 20, 20, 22, 22, 20, 20, 20, 20, 20, 20, 2, 20, 20, 26, 26, 26}, ...
        'ColumnWidth', {'1x', '1x'}, ...
        'Padding',     [3 2 3 2], ...
        'RowSpacing',  2, ...
        'ColumnSpacing', 3);

    % ── Row 1: Scale bar checkbox ────────────────────────────────────────
    cbScaleBar = uicheckbox(measureInnerGL, ...
        'Text',    'Scale Bar', ...
        'Value',   false, ...
        'Enable',  'off', ...
        'ValueChangedFcn', callbacks.onScaleBarToggle, ...
        'Tooltip', 'Overlay a draggable scale bar (requires pixel size calibration)');
    cbScaleBar.Layout.Row = 1; cbScaleBar.Layout.Column = [1 2];

    % ── Row 2: Scale bar colour dropdown + font size spinner ─────────────
    sqSB = char(9632);   % ■ Unicode filled square swatch
    ddScaleBarColor = uidropdown(measureInnerGL, ...
        'Items',     {[sqSB ' White'], [sqSB ' Cyan'], [sqSB ' Yellow'], ...
                      [sqSB ' Red'],   [sqSB ' Black']}, ...
        'ItemsData', {'White', 'Cyan', 'Yellow', 'Red', 'Black'}, ...
        'Value',           'White', ...
        'ValueChangedFcn', callbacks.onScaleBarColorChange, ...
        'BackgroundColor', [0.25 0.25 0.25], ...
        'FontColor',       [1 1 1], ...
        'FontSize', 11, ...
        'Enable',          'off', ...
        'Tooltip',         'Scale bar colour: White / Cyan / Yellow / Red / Black');
    ddScaleBarColor.Layout.Row = 2; ddScaleBarColor.Layout.Column = 1;

    spnScaleBarFont = uispinner(measureInnerGL, ...
        'Value', 30, 'Limits', [6 72], 'Step', 1, ...
        'ValueChangedFcn', callbacks.onScaleBarFontChange, ...
        'Enable', 'off', ...
        'Tooltip', 'Scale bar label font size (pt)');
    spnScaleBarFont.Layout.Row = 2; spnScaleBarFont.Layout.Column = 2;

    % ── Row 3: Explicit length override + unit dropdown ──────────────────
    efScaleBarLen = uieditfield(measureInnerGL, 'numeric', ...
        'Value', 0, 'Limits', [0 Inf], ...
        'ValueDisplayFormat', '%g', ...
        'Placeholder', 'auto', ...
        'Enable', 'off', ...
        'ValueChangedFcn', callbacks.onScaleBarFontChange, ...
        'Tooltip', 'Override scale bar length (0 = auto-pick a nice round value)');
    efScaleBarLen.Layout.Row = 3; efScaleBarLen.Layout.Column = 1;

    ddScaleBarUnit = uidropdown(measureInnerGL, ...
        'Items', {'auto', 'nm', 'μm', 'Å', 'mm', 'pm'}, ...
        'ItemsData', {'auto', 'nm', 'um', 'A', 'mm', 'pm'}, ...
        'Value', 'auto', ...
        'Enable', 'off', ...
        'ValueChangedFcn', callbacks.onScaleBarFontChange, ...
        'Tooltip', 'Unit for the length override; "auto" uses the image calibration unit');
    ddScaleBarUnit.Layout.Row = 3; ddScaleBarUnit.Layout.Column = 2;

    % ── Row 4: Line Profile + Box Profile buttons ─────────────────────────
    btnLineProfile = uibutton(measureInnerGL, 'Text', 'Line Profile', ...
        'ButtonPushedFcn', callbacks.onLineProfile, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Click two points to extract an intensity profile (Esc to cancel)');
    btnLineProfile.Layout.Row = 4; btnLineProfile.Layout.Column = 1;

    btnBoxProfile = uibutton(measureInnerGL, 'Text', 'Box Profile', ...
        'ButtonPushedFcn', callbacks.onBoxProfile, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Click two points to define a rotated rectangle; intensity averaged across its width (Esc to cancel)');
    btnBoxProfile.Layout.Row = 4; btnBoxProfile.Layout.Column = 2;

    % ── Row 5: Distance + Angle buttons ──────────────────────────────────
    btnDistance = uibutton(measureInnerGL, 'Text', 'Distance', ...
        'ButtonPushedFcn', callbacks.onDistance, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Click two points to measure distance (Esc to cancel)');
    btnDistance.Layout.Row = 5; btnDistance.Layout.Column = 1;

    btnAngle = uibutton(measureInnerGL, 'Text', 'Angle', ...
        'ButtonPushedFcn', callbacks.onAngleAction, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Click 3 points (vertex, ray1, ray2) to measure angle (Esc to cancel)');
    btnAngle.Layout.Row = 5; btnAngle.Layout.Column = 2;

    % (Row 6 is a 2-px spacer — no widgets)

    % ── Row 7: Export CSV (last line profile) ────────────────────────────
    btnExportProfile = uibutton(measureInnerGL, 'Text', 'Export CSV', ...
        'ButtonPushedFcn', callbacks.onExportProfile, ...
        'BackgroundColor', palette.export, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Save the last line profile to a CSV file');
    btnExportProfile.Layout.Row = 7; btnExportProfile.Layout.Column = [1 2];

    % ── Row 8: Clear All + Remove buttons ────────────────────────────────
    btnClearOverlays = uibutton(measureInnerGL, 'Text', 'Clear All', ...
        'ButtonPushedFcn', callbacks.onClearOverlays, ...
        'BackgroundColor', palette.danger, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Remove all measurement overlays from the image');
    btnClearOverlays.Layout.Row = 8; btnClearOverlays.Layout.Column = 1;

    btnRemoveMeas = uibutton(measureInnerGL, 'Text', 'Remove', ...
        'ButtonPushedFcn', callbacks.onRemoveSelected, ...
        'BackgroundColor', palette.danger, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Remove the selected measurement (click a line first), or press Delete');
    btnRemoveMeas.Layout.Row = 8; btnRemoveMeas.Layout.Column = 2;

    % ── Row 9: Tilt correction checkbox + angle spinner ──────────────────
    % Auto-populated from image metadata when present (FEI StageT / Bruker
    % Tilt). When active, Distance, Line Profile, Polyline, and Angle
    % measurements are rescaled along the foreshortened axis. The trig
    % factor depends on the Geometry dropdown on Row 10.
    cbTiltCorrect = uicheckbox(measureInnerGL, ...
        'Text',            'Tilt corr.', ...
        'Value',           false, ...
        'Enable',          'off', ...
        'Tooltip',         ['Rescale the foreshortened axis of distance / ' ...
                            'profile / polyline / angle measurements to ' ...
                            'recover true sample-frame lengths. Factor ' ...
                            'depends on Geometry: 1/sin(θ) for cross-' ...
                            'section, 1/cos(θ) for plan-view surface. ' ...
                            'Auto-detected from SEM metadata.']);
    cbTiltCorrect.Layout.Row = 9; cbTiltCorrect.Layout.Column = 1;

    spnTiltAngle = uispinner(measureInnerGL, ...
        'Value',           0, ...
        'Limits',          [-89.9 89.9], ...
        'Step',            1, ...
        'ValueDisplayFormat', '%.1f°', ...
        'Enable',          'off', ...
        'Tooltip',         ['Stage tilt angle θ in degrees (override the ' ...
                            'metadata-detected value). Applied as 1/sin(θ) ' ...
                            'for cross-section geometry, 1/cos(θ) for ' ...
                            'surface geometry.']);
    spnTiltAngle.Layout.Row = 9; spnTiltAngle.Layout.Column = 2;

    % ── Row 10: Tilt geometry selector ───────────────────────────────────
    % Default = Cross-section (standard FIB cross-section workflow).
    % Switch to Surface for plan-view SEM of a stage-tilted top surface.
    ddTiltGeometry = uidropdown(measureInnerGL, ...
        'Items',           {'Cross-section', 'Surface'}, ...
        'ItemsData',       {'CrossSection', 'Surface'}, ...
        'Value',           'CrossSection', ...
        'Enable',          'off', ...
        'Tooltip',         ['Cross-section: FIB cross-section viewed at tilt ' ...
                            'θ — true depth recovered via 1/sin(θ). ' ...
                            'Surface: plan-view SEM of tilted top surface ' ...
                            '— true lateral length recovered via 1/cos(θ). ' ...
                            'See docs/theory/imaging.md for the derivation.']);
    ddTiltGeometry.Layout.Row = 10; ddTiltGeometry.Layout.Column = [1 2];

    % ── Row 11: Export Table + Diff Rings ────────────────────────────────
    btnExportMeasure = uibutton(measureInnerGL, 'Text', 'Export Table', ...
        'ButtonPushedFcn', callbacks.onExportMeasure, ...
        'BackgroundColor', palette.export, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Export all measurements (distances, angles, ROI stats) to CSV');
    btnExportMeasure.Layout.Row = 11; btnExportMeasure.Layout.Column = 1;

    btnDiffRings = uibutton(measureInnerGL, 'Text', 'Diff Rings', ...
        'ButtonPushedFcn', callbacks.onDiffRings, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Overlay calibrated diffraction rings (d-spacing)');
    btnDiffRings.Layout.Row = 11; btnDiffRings.Layout.Column = 2;

    % ── Row 12: ROI Manager ───────────────────────────────────────────────
    btnROIManager = uibutton(measureInnerGL, 'Text', 'ROI Manager', ...
        'ButtonPushedFcn', callbacks.onROIManager, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Manage saved ROIs with properties table and CSV export');
    btnROIManager.Layout.Row = 12; btnROIManager.Layout.Column = [1 2];

    % ── Row 13: Calibrate from Scale Bar ─────────────────────────────────
    btnCalibrateBar = uibutton(measureInnerGL, 'Text', 'Calibrate Bar', ...
        'ButtonPushedFcn', callbacks.onCalibrateBar, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip', 'Draw along a scale bar in the image to calibrate pixel size; auto-detect available');
    btnCalibrateBar.Layout.Row = 13; btnCalibrateBar.Layout.Column = [1 2];

    % ── Row 14: d-Spacing + Profile width spinner ────────────────────────
    btnDSpacing = uibutton(measureInnerGL, 'Text', 'd-Spacing', ...
        'ButtonPushedFcn', callbacks.onDSpacing, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Click FFT spots to measure d-spacing (requires calibration)');
    btnDSpacing.Layout.Row = 14; btnDSpacing.Layout.Column = 1;

    spnProfileWidth = uispinner(measureInnerGL, ...
        'Value', 1, 'Limits', [1 200], 'Step', 2, ...
        'Enable', 'off', ...
        'Tooltip', 'Line profile averaging width (px) — 1 = single pixel; also sets default width for Box Profile');
    spnProfileWidth.Layout.Row = 14; spnProfileWidth.Layout.Column = 2;

    % ── Row 15: ROI shape picker + Draw ROI button ───────────────────────
    ddROIShape = uidropdown(measureInnerGL, ...
        'Items',    {'Rectangle', 'Circle', 'Polyline'}, ...
        'Value',    'Rectangle', ...
        'Enable',   'off', ...
        'Tooltip',  'Choose ROI shape — Rectangle (drag), Circle (click center then edge), Polyline (click vertices, double-click to finish)');
    ddROIShape.Layout.Row = 15; ddROIShape.Layout.Column = 1;

    btnDrawROI = uibutton(measureInnerGL, 'Text', 'Draw ROI', ...
        'ButtonPushedFcn', callbacks.onDrawROI, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Start drawing the ROI shape selected in the dropdown (Esc to cancel)');
    btnDrawROI.Layout.Row = 15; btnDrawROI.Layout.Column = 2;

    % ── Row 16: Invert Image ─────────────────────────────────────────────
    btnInvertImg = uibutton(measureInnerGL, 'Text', 'Invert Image', ...
        'ButtonPushedFcn', callbacks.onInvertImage, ...
        'BackgroundColor', palette.tool, ...
        'FontColor',       palette.fg, ...
        'Enable',          'off', ...
        'Tooltip',         'Invert pixel values: img = max - img (bright-field / dark-field)');
    btnInvertImg.Layout.Row = 16; btnInvertImg.Layout.Column = [1 2];

    % (Row 17 is a 2-px spacer — no widgets)

    % ── Rows 18-19: Measurement statistics / Batch / Export to DP ────────
    btnMeasStats = uibutton(measureInnerGL, 'Text', 'Meas Stats', ...
        'ButtonPushedFcn', callbacks.onMeasurementStats, ...
        'BackgroundColor', palette.export, ...
        'FontColor', palette.fg, ...
        'Enable', 'off', ...
        'Tooltip', 'Show statistics for all measurements (mean, std, histogram)');
    btnMeasStats.Layout.Row = 18; btnMeasStats.Layout.Column = 1;

    btnBatchMeas = uibutton(measureInnerGL, 'Text', 'Batch Meas', ...
        'ButtonPushedFcn', callbacks.onBatchMeasurement, ...
        'BackgroundColor', palette.export, ...
        'FontColor', palette.fg, ...
        'Enable', 'off', ...
        'Tooltip', 'Apply measurement template across all loaded images');
    btnBatchMeas.Layout.Row = 18; btnBatchMeas.Layout.Column = 2;

    btnExportToDP = uibutton(measureInnerGL, 'Text', 'Profile → BosonPlotter', ...
        'ButtonPushedFcn', callbacks.onExportProfileToDP, ...
        'BackgroundColor', palette.export, ...
        'FontColor', palette.fg, ...
        'Enable', 'off', ...
        'Tooltip', 'Send last line profile to BosonPlotter as standard data struct');
    btnExportToDP.Layout.Row = 19; btnExportToDP.Layout.Column = [1 2];

    % ── Rows 20-22: Measurement style controls ────────────────────────────
    lblMeasLabelFont = uilabel(measureInnerGL, 'Text', 'Label font:', ...
        'HorizontalAlignment', 'right', 'FontSize', 11);
    lblMeasLabelFont.Layout.Row = 20; lblMeasLabelFont.Layout.Column = 1;

    spnMeasLabelFont = uispinner(measureInnerGL, ...
        'Value', 16, 'Limits', [6 72], 'Step', 1, ...
        'FontSize', 11, ...
        'Tooltip', 'Font size — click a label to target one, otherwise applies to all', ...
        'ValueChangedFcn', @(src,~) callbacks.panelApplyLabelFont(src.Value), ...
        'Enable', 'off');
    spnMeasLabelFont.Layout.Row = 20; spnMeasLabelFont.Layout.Column = 2;

    lblMeasSymbol = uilabel(measureInnerGL, 'Text', 'End symbol:', ...
        'HorizontalAlignment', 'right', 'FontSize', 11);
    lblMeasSymbol.Layout.Row = 21; lblMeasSymbol.Layout.Column = 1;

    ddMeasSymbol = uidropdown(measureInnerGL, ...
        'Items', {'Circle', 'Cross', 'Square', 'None'}, ...
        'ItemsData', {'circle', 'cross', 'square', 'none'}, ...
        'Value', 'circle', ...
        'FontSize', 11, ...
        'Tooltip', 'Endpoint symbol — click a line to target one, otherwise applies to all', ...
        'ValueChangedFcn', @(src,~) callbacks.panelApplySymbol(src.Value), ...
        'Enable', 'off');
    ddMeasSymbol.Layout.Row = 21; ddMeasSymbol.Layout.Column = 2;

    lblMeasColor = uilabel(measureInnerGL, 'Text', 'Line color:', ...
        'HorizontalAlignment', 'right', 'FontSize', 11);
    lblMeasColor.Layout.Row = 22; lblMeasColor.Layout.Column = 1;

    ddMeasColor = uidropdown(measureInnerGL, ...
        'Items', {'White', 'Cyan', 'Yellow', 'Red', 'Green', 'Blue'}, ...
        'ItemsData', {[1 1 1], [0 1 1], [1 1 0], [1 0 0], [0 0.8 0], [0 0.4 1]}, ...
        'Value', [1 1 1], ...
        'FontSize', 11, ...
        'Tooltip', 'Line color — click a line to target one, otherwise applies to all', ...
        'ValueChangedFcn', @(src,~) callbacks.panelApplyColor(src.Value), ...
        'Enable', 'off');
    ddMeasColor.Layout.Row = 22; ddMeasColor.Layout.Column = 2;

    % ── Pack return struct ────────────────────────────────────────────────
    s.measureInnerGL  = measureInnerGL;
    s.cbScaleBar      = cbScaleBar;
    s.ddScaleBarColor = ddScaleBarColor;
    s.spnScaleBarFont = spnScaleBarFont;
    s.efScaleBarLen   = efScaleBarLen;
    s.ddScaleBarUnit  = ddScaleBarUnit;
    s.btnLineProfile  = btnLineProfile;
    s.btnBoxProfile   = btnBoxProfile;
    s.btnDistance     = btnDistance;
    s.btnExportProfile = btnExportProfile;
    s.btnAngle        = btnAngle;
    s.btnClearOverlays = btnClearOverlays;
    s.btnRemoveMeas   = btnRemoveMeas;
    s.cbTiltCorrect   = cbTiltCorrect;
    s.spnTiltAngle    = spnTiltAngle;
    s.ddTiltGeometry  = ddTiltGeometry;
    s.btnExportMeasure = btnExportMeasure;
    s.btnDiffRings    = btnDiffRings;
    s.btnROIManager   = btnROIManager;
    s.btnCalibrateBar = btnCalibrateBar;
    s.btnDSpacing     = btnDSpacing;
    s.spnProfileWidth = spnProfileWidth;
    s.ddROIShape      = ddROIShape;
    s.btnDrawROI      = btnDrawROI;
    s.btnInvertImg    = btnInvertImg;
    s.btnMeasStats    = btnMeasStats;
    s.btnBatchMeas    = btnBatchMeas;
    s.btnExportToDP   = btnExportToDP;
    s.lblMeasLabelFont = lblMeasLabelFont;
    s.spnMeasLabelFont = spnMeasLabelFont;
    s.lblMeasSymbol   = lblMeasSymbol;
    s.ddMeasSymbol    = ddMeasSymbol;
    s.lblMeasColor    = lblMeasColor;
    s.ddMeasColor     = ddMeasColor;

end
