function buildGIFDialog(imageNames, btnColors, onCreateCb)
%BUILDGIFDIALOG  Modal dialog for creating animated GIF from loaded images.
    arguments
        imageNames  cell
        btnColors   struct
        onCreateCb  function_handle
    end

    nImg = numel(imageNames);

    dlg = uifigure('Name', 'Create Animated GIF', ...
        'Position', [200 200 400 370], ...
        'Resize', 'off', ...
        'WindowStyle', 'modal');
    dlgGL = uigridlayout(dlg, [8 2], ...
        'RowHeight', {22, 120, 22, 22, 22, 22, 10, 28}, ...
        'ColumnWidth', {120, '1x'}, ...
        'Padding', [10 10 10 10], ...
        'RowSpacing', 6);

    lblGIFSelect = uilabel(dlgGL, 'Text', 'Select images:', ...
        'FontWeight', 'bold', 'FontSize', 11);
    lblGIFSelect.Layout.Row = 1;

    lbGIFImages = uilistbox(dlgGL, ...
        'Items', imageNames, ...
        'ItemsData', 1:nImg, ...
        'Multiselect', 'on', ...
        'Value', 1:nImg);
    lbGIFImages.Layout.Row = 2;
    lbGIFImages.Layout.Column = [1 2];

    lblDelay = uilabel(dlgGL, 'Text', 'Frame delay (s):', ...
        'HorizontalAlignment', 'right');    lblDelay.Layout.Row = 3; lblDelay.Layout.Column = 1;
    efDelay = uieditfield(dlgGL, 'numeric', ...
        'Value', 0.5, 'Limits', [0.02 10], ...
        'Tooltip', 'Seconds per frame (0.02 – 10)');
    efDelay.Layout.Row = 3; efDelay.Layout.Column = 2;

    lblLoop = uilabel(dlgGL, 'Text', 'Loop:', ...
        'HorizontalAlignment', 'right');    lblLoop.Layout.Row = 4; lblLoop.Layout.Column = 1;
    ddLoop = uidropdown(dlgGL, ...
        'Items', {'Infinite', '1', '2', '3', '5', '10'}, ...
        'ItemsData', {Inf, 1, 2, 3, 5, 10}, ...
        'Value', Inf, ...
        'Tooltip', 'Number of times the GIF loops');
    ddLoop.Layout.Row = 4; ddLoop.Layout.Column = 2;

    cbScaleBarGIF = uicheckbox(dlgGL, ...
        'Text', 'Include scale bar', ...
        'Value', true, ...
        'Tooltip', 'Add a scale bar at same position on every frame');
    cbScaleBarGIF.Layout.Row = 5;
    cbScaleBarGIF.Layout.Column = [1 2];

    lblBarColor = uilabel(dlgGL, 'Text', 'Bar color:', ...
        'HorizontalAlignment', 'right');    lblBarColor.Layout.Row = 6; lblBarColor.Layout.Column = 1;
    ddBarColor = uidropdown(dlgGL, ...
        'Items', {'White', 'Black'}, ...
        'Value', 'White', ...
        'Tooltip', 'Scale bar and label color');
    ddBarColor.Layout.Row = 6; ddBarColor.Layout.Column = 2;

    btnGo = uibutton(dlgGL, 'Text', 'Create GIF', ...
        'BackgroundColor', btnColors.primary, ...
        'FontColor', btnColors.fg);
    btnGo.Layout.Row = 8; btnGo.Layout.Column = 1;

    btnCancel = uibutton(dlgGL, 'Text', 'Cancel', ...
        'BackgroundColor', btnColors.tool, ...
        'FontColor', btnColors.fg, ...
        'ButtonPushedFcn', @(~,~) close(dlg));    btnCancel.Layout.Row = 8; btnCancel.Layout.Column = 2;

    btnGo.ButtonPushedFcn = @(~,~) onCreateCb( ...
        dlg, lbGIFImages, efDelay, ddLoop, cbScaleBarGIF, ddBarColor);
end
