function s = buildEDSPanel(parent, tk, palette, callbacks)
%BUILDEDSPANEL  Construct the EDS Channels sub-panel for FermiViewer.
%
% Syntax
%   s = emViewer.buildEDSPanel(parent, tk, palette, callbacks)
%
% Inputs
%   parent     uigridlayout (toolsGL) that hosts the panel.
%              The function creates pnlEDS inside parent and sets
%              its Layout.Row = 12.
%   tk         UX tokens struct (unused here, reserved for future theming)
%   palette    struct of semantic button colours:
%                .primary  — green, primary actions
%                .tool     — gray, secondary tools
%                .danger   — red, destructive actions
%                .export   — blue, export actions
%                .fg       — white foreground text
%   callbacks  struct of function handles:
%                .onEnterEDS             — Enter EDS mode toggle
%                .onEDSListChange        — dispatches 'add' or 'remove'
%                .onEDSChannelSelected   — channel list selection changed
%                .onEDSChannelPropChanged — dispatches 'color', 'visible',
%                                          'intensity', 'label'
%                .onExportEDSComposite   — export blended RGB composite
%                .onAssignElements       — assign element symbols to channels
%                .onQuantifyCL           — Cliff-Lorimer quantification
%                .onCompositionProfile   — line composition profile
%                .onROIComposition       — ROI mean composition
%                .onQuantifyZAF          — ZAF-corrected quantification
%
% Outputs
%   s   struct of widget handles:
%         .pnlEDS               — the outer uipanel (parented to toolsGL)
%         .btnEnterEDS          — Enter/Exit EDS mode button
%         .btnAddChannel        — Add Channel button
%         .btnRemoveChannel     — Remove channel button
%         .lbEDSChannels        — channel list box
%         .EDS_COLORS           — cell array of available colour names
%         .ddChannelColor       — channel colour dropdown
%         .cbChannelVisible     — channel visibility checkbox
%         .lblEDSIntensity      — intensity value label
%         .sldChannelIntensity  — channel intensity slider
%         .efChannelLabel       — channel label edit field
%         .btnExportComposite   — Export RGB button
%         .btnAssignElements    — Assign Elements button
%         .btnQuantifyCL        — Quantify (Cliff-Lorimer) button
%         .btnCompositionProfile — Composition Profile button
%         .btnROIComposition    — ROI Composition button
%         .edtEDSThickness      — specimen thickness edit field
%         .edtEDSTakeOff        — take-off angle edit field
%         .btnQuantifyZAF       — Quantify ZAF button
%
% Examples
%   eds_ = emViewer.buildEDSPanel(toolsGL, struct(), palette, callbacks);
%   btnEnterEDS = eds_.btnEnterEDS;

    arguments
        parent
        tk         struct  %#ok<INUSA>  % reserved for future theming
        palette    struct
        callbacks  struct
    end

    % Palette shorthands
    BTN_PRIMARY = palette.primary;
    BTN_TOOL    = palette.tool;
    BTN_DANGER  = palette.danger;
    BTN_EXPORT  = palette.export;
    BTN_FG      = palette.fg;

    % ── Outer panel (parented to toolsGL, row 12) ────────────────────────
    s.pnlEDS = uipanel(parent, 'BorderType', 'line');
    s.pnlEDS.Layout.Row = 12;

    s.edsInnerGL = uigridlayout(s.pnlEDS, [14 2], ...
        'RowHeight', {28, 28, 100, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28}, ...
        'ColumnWidth', {'1x', '1x'}, ...
        'Padding', [4 4 4 4], ...
        'RowSpacing', 3);

    % ── Row 1: Enter EDS Mode (full-width) ───────────────────────────────
    s.btnEnterEDS = uibutton(s.edsInnerGL, 'Text', 'Enter EDS Mode', ...
        'ButtonPushedFcn', callbacks.onEnterEDS, ...
        'BackgroundColor', BTN_PRIMARY, ...
        'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Enable', 'off', ...
        'Tooltip', 'Enter multi-channel EDS false-color composite mode');
    s.btnEnterEDS.Layout.Row = 1; s.btnEnterEDS.Layout.Column = [1 2];

    % ── Row 2: Add / Remove channel ──────────────────────────────────────
    s.btnAddChannel = uibutton(s.edsInnerGL, 'Text', 'Add Channel', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEDSListChange('add'), ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Add active image as an EDS channel');
    s.btnAddChannel.Layout.Row = 2; s.btnAddChannel.Layout.Column = 1;

    s.btnRemoveChannel = uibutton(s.edsInnerGL, 'Text', 'Remove', ...
        'ButtonPushedFcn', @(~,~) callbacks.onEDSListChange('remove'), ...
        'BackgroundColor', BTN_DANGER, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Remove selected channel from composite');
    s.btnRemoveChannel.Layout.Row = 2; s.btnRemoveChannel.Layout.Column = 2;

    % ── Row 3: Channel list box ───────────────────────────────────────────
    s.lbEDSChannels = uilistbox(s.edsInnerGL, ...
        'Items', {'(no channels)'}, ...
        'ItemsData', 0, ...
        'ValueChangedFcn', callbacks.onEDSChannelSelected, ...
        'FontSize', 11);
    s.lbEDSChannels.Layout.Row = 3; s.lbEDSChannels.Layout.Column = [1 2];

    % ── Row 4: Color label + dropdown ────────────────────────────────────
    s.EDS_COLORS = {'red', 'green', 'blue', 'cyan', 'magenta', 'yellow', 'white'};

    lblEDSColor = uilabel(s.edsInnerGL, 'Text', 'Color:', ...
        'FontSize', 11, 'HorizontalAlignment', 'right');
    lblEDSColor.Layout.Row = 4; lblEDSColor.Layout.Column = 1;

    s.ddChannelColor = uidropdown(s.edsInnerGL, ...
        'Items', s.EDS_COLORS, ...
        'Value', 'red', ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('color'), ...
        'Enable', 'off', ...
        'Tooltip', 'Pseudo-color for this channel');
    s.ddChannelColor.Layout.Row = 4; s.ddChannelColor.Layout.Column = 2;

    % ── Row 5: Visible checkbox + intensity label ─────────────────────────
    s.cbChannelVisible = uicheckbox(s.edsInnerGL, ...
        'Text', 'Visible', ...
        'Value', true, ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('visible'), ...
        'Enable', 'off');
    s.cbChannelVisible.Layout.Row = 5; s.cbChannelVisible.Layout.Column = 1;

    s.lblEDSIntensity = uilabel(s.edsInnerGL, 'Text', 'Int: 1.00', ...
        'FontSize', 11, 'HorizontalAlignment', 'center');
    s.lblEDSIntensity.Layout.Row = 5; s.lblEDSIntensity.Layout.Column = 2;

    % ── Row 6: Intensity slider (full-width) ──────────────────────────────
    s.sldChannelIntensity = uislider(s.edsInnerGL, ...
        'Limits', [0 1], ...
        'Value', 1, ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('intensity'), ...
        'Enable', 'off');
    s.sldChannelIntensity.Layout.Row = 6; s.sldChannelIntensity.Layout.Column = [1 2];

    % ── Row 7: Channel label edit field (full-width) ──────────────────────
    s.efChannelLabel = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '', ...
        'ValueChangedFcn', @(~,~) callbacks.onEDSChannelPropChanged('label'), ...
        'Enable', 'off', ...
        'Placeholder', 'Channel label');
    s.efChannelLabel.Layout.Row = 7; s.efChannelLabel.Layout.Column = [1 2];

    % ── Row 8: Export RGB (full-width) ────────────────────────────────────
    s.btnExportComposite = uibutton(s.edsInnerGL, 'Text', 'Export RGB', ...
        'ButtonPushedFcn', callbacks.onExportEDSComposite, ...
        'BackgroundColor', BTN_EXPORT, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Save the blended RGB composite to PNG/TIFF');
    s.btnExportComposite.Layout.Row = 8; s.btnExportComposite.Layout.Column = [1 2];

    % ── EDS Quantification controls (rows 9-12) ───────────────────────────

    % Row 9: Assign Elements (full-width)
    s.btnAssignElements = uibutton(s.edsInnerGL, 'Text', 'Assign Elements', ...
        'ButtonPushedFcn', callbacks.onAssignElements, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Assign element symbols to EDS channels');
    s.btnAssignElements.Layout.Row = 9; s.btnAssignElements.Layout.Column = [1 2];

    % Row 10: Quantify (Cliff-Lorimer) (full-width)
    s.btnQuantifyCL = uibutton(s.edsInnerGL, 'Text', 'Quantify (Cliff-Lorimer)', ...
        'ButtonPushedFcn', callbacks.onQuantifyCL, ...
        'BackgroundColor', BTN_PRIMARY, 'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Enable', 'off', ...
        'Tooltip', 'Compute atomic% and weight% maps using Cliff-Lorimer method');
    s.btnQuantifyCL.Layout.Row = 10; s.btnQuantifyCL.Layout.Column = [1 2];

    % Row 11: Composition Profile (full-width)
    s.btnCompositionProfile = uibutton(s.edsInnerGL, 'Text', 'Composition Profile', ...
        'ButtonPushedFcn', callbacks.onCompositionProfile, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click two points for a line composition profile');
    s.btnCompositionProfile.Layout.Row = 11; s.btnCompositionProfile.Layout.Column = [1 2];

    % Row 12: ROI Composition (full-width)
    s.btnROIComposition = uibutton(s.edsInnerGL, 'Text', 'ROI Composition', ...
        'ButtonPushedFcn', callbacks.onROIComposition, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Click two corners for mean composition in ROI');
    s.btnROIComposition.Layout.Row = 12; s.btnROIComposition.Layout.Column = [1 2];

    % ── Row 13: Thickness + Take-off angle for ZAF ───────────────────────
    s.edtEDSThickness = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '100', 'Placeholder', 't (nm)');
    s.edtEDSThickness.Layout.Row = 13; s.edtEDSThickness.Layout.Column = 1;

    s.edtEDSTakeOff = uieditfield(s.edsInnerGL, 'text', ...
        'Value', '20', 'Placeholder', 'angle (deg)');
    s.edtEDSTakeOff.Layout.Row = 13; s.edtEDSTakeOff.Layout.Column = 2;

    % ── Row 14: Quantify ZAF (full-width) ────────────────────────────────
    s.btnQuantifyZAF = uibutton(s.edsInnerGL, 'Text', 'Quantify ZAF', ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, ...
        'Tooltip', 'ZAF-corrected quantification (thick specimens)', ...
        'Enable', 'off', ...
        'ButtonPushedFcn', callbacks.onQuantifyZAF);
    s.btnQuantifyZAF.Layout.Row = 14; s.btnQuantifyZAF.Layout.Column = [1 2];
end
