function s = buildTransformPanel(parent, tk, palette, callbacks)
%BUILDTRANSFORMPANEL  Build the Process tab-group (Transform / Filter /
%   FFT & Analysis / Surface & Stack) inner UI for FermiViewer.
%
% Syntax
%   s = fermiViewer.buildTransformPanel(parent, tk, palette, callbacks)
%
% Inputs
%   parent     uipanel (pnlProcess) that hosts the inner grid and tab-group.
%   tk         UX tokens struct (unused here, reserved for future theming).
%   palette    struct of semantic button colours:
%                .tool    — gray, secondary tools
%                .export  — slate, export actions
%                .danger  — red, destructive actions
%                .fg      — white foreground text
%   callbacks  struct of function handles — one per interactive widget:
%
%              Transform tab:
%                .onRotateFlip        — @(action) dispatcher ('rot90cw', etc.)
%                .onZoomBox           — @onZoomBox (also called with 'dims' arg)
%                .onResetZoom         — @onResetZoom
%                .onCropImage         — @onCropImage
%                .onExportAction      — @(action) dispatcher ('saveCrop', 'batchCrop')
%                .onBinImage          — @onBinImage
%                .onSetPixelSize      — @onSetPixelSize
%
%              Filter tab:
%                .onGaussianFilter    — @onGaussianFilter
%                .onMedianFilter      — @onMedianFilter
%                .onCLAHE             — @onCLAHE
%                .onSharpen           — @onSharpen
%                .onMorphOp           — @onMorphOp
%                .onButterworth       — @onButterworth
%                .onFFTMask           — @onFFTMask
%                .onLiveThreshold     — @onLiveThreshold
%                .onMultiOtsu         — @onMultiOtsu
%                .onUndoFilters       — @onUndoFilters
%                .onPixelInspectorToggle — @onPixelInspectorToggle
%
%              FFT & Analysis tab:
%                .onShowFFT           — @onShowFFT
%                .onLiveFFTToggle     — @onLiveFFTToggle
%                .onRadialProfile     — @onRadialProfile
%                .onAzIntegrate       — @onAzIntegrate
%                .onDiffractionAction — @(action) dispatcher ('latticeMeasure')
%                .onGPA               — @onGPA
%                .onCTFEstimate       — @onCTFEstimate
%                .onNoiseEstimate     — @onNoiseEstimate
%                .onTemplateMatch     — @onTemplateMatch
%                .onInterfaceFit      — @onInterfaceFit
%                .onDefectCount       — @onDefectCount
%
%              Surface & Stack tab:
%                .onPlaneLevel        — @onPlaneLevel
%                .onRoughness         — @onRoughness
%                .on3DSurface         — @on3DSurface
%                .onSurfacePlot       — @onSurfacePlot
%                .onBackProject       — @onBackProject
%                .onParticleCount     — @onParticleCount
%                .onWatershed         — @onWatershed
%                .onAlignStack        — @onAlignStack
%                .onStitchImages      — @onStitchImages
%                .onMontage           — @onMontage
%
% Output
%   s          struct of all created widget handles referenced elsewhere
%              in FermiViewer.m.  Fields (alphabetical within tab):
%
%              Process container:
%                .processTabGrids   — {transformGL, filterGL, analysisGL, surfaceGL}
%
%              Transform tab:
%                .btnRotCW, .btnRotCCW, .btnFlipH, .btnFlipV,
%                .btnZoomBox, .btnResetZoom, .btnCropImage, .btnSaveCrop,
%                .btnBatchCrop, .btnBinImage, .btnSetPixelSize, .btnZoomDims
%
%              Filter tab:
%                .btnGaussian, .btnMedian, .btnCLAHE, .btnSharpen,
%                .btnMorphOp, .btnButterworth, .btnFFTMask, .btnLiveThresh,
%                .btnMultiOtsu, .btnUndoFilters, .cbPixelInspector
%
%              FFT & Analysis tab:
%                .btnShowFFT, .btnLiveFFT, .btnRadialProfile, .btnAzIntegrate,
%                .btnLatticeMeasure, .btnGPA, .btnCTF, .btnNoiseEstimate,
%                .btnTemplateMatch, .btnInterfaceFit, .btnDefectCount
%
%              Surface & Stack tab:
%                .btnPlaneLevel, .btnRoughness, .btn3DSurface, .btnSurfacePlot,
%                .btnBackProject, .btnParticles, .btnWatershed, .btnAlignStack,
%                .btnStitchImages, .btnMontage
%
% Examples
%   tfCb_ = struct('onRotateFlip', @onRotateFlip, ...);
%   tf_ = fermiViewer.buildTransformPanel(pnlProcess, tk, palette, tfCb_);
%   processTabGrids = tf_.processTabGrids;
%   btnRotCW        = tf_.btnRotCW;

    arguments
        parent
        tk         struct  % uxTokens — section-header colours (Variant A)
        palette    struct
        callbacks  struct
    end

    % Palette shorthands. Variant A flattens the section buttons to one
    % neutral tone (BTN_TOOL); only destructive actions keep the danger red.
    BTN_TOOL   = palette.tool;
    BTN_DANGER = palette.danger;
    BTN_FG     = palette.fg;

    % Variant A redesign uses uxTokens for the section headers; tolerate an
    % empty/struct() tk by falling back to the dark palette.
    if ~isstruct(tk) || ~isfield(tk, 'color')
        tk = fermiViewer.chrome.uxTokens('dark');
    end

    % ── Process inner wrapper ─────────────────────────────────────────────
    % A scrollable column of collapsible sections (Variant A) replaces the
    % former 4-tab uitabgroup. Each former tab is now a section; every
    % button's variable name + callback is preserved (only the container
    % changed), so setToolsEnabled and the rest of the file are unaffected.
    processInnerGL = uigridlayout(parent, [1 1], ...
        'Padding', [2 2 2 2], ...
        'RowHeight', {'1x'}, 'ColumnWidth', {'1x'});

    sectionsCol = uigridlayout(processInnerGL, [4 1], ...
        'RowHeight', {'fit','fit','fit','fit'}, 'ColumnWidth', {'1x'}, ...
        'Padding', [0 0 0 0], 'RowSpacing', 4, 'Scrollable', 'on');
    sectionsCol.Layout.Row = 1; sectionsCol.Layout.Column = 1;

    tabDef = struct( ...
        'RowHeight',   {repmat({22}, 1, 6)}, ...
        'ColumnWidth', {{'1x','1x'}}, ...
        'Padding',     [3 3 3 3], ...
        'RowSpacing',  3, ...
        'ColumnSpacing', 3);

    % ── Section 1: Transform ─────────────────────────────────────────────
    secTransform = localSection(sectionsCol, tk, 'Transform');
    transformGL = uigridlayout(secTransform.body, [7 2], ...
        'RowHeight', [tabDef.RowHeight {22}], 'ColumnWidth', tabDef.ColumnWidth, ...
        'Padding', tabDef.Padding, 'RowSpacing', tabDef.RowSpacing, ...
        'ColumnSpacing', tabDef.ColumnSpacing);

    s.btnRotCW = uibutton(transformGL, 'Text', 'Rot 90 CW', ...
        'ButtonPushedFcn', @(~,~) callbacks.onRotateFlip('rot90cw'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Rotate image 90° clockwise');
    s.btnRotCW.Layout.Row = 1; s.btnRotCW.Layout.Column = 1;

    s.btnRotCCW = uibutton(transformGL, 'Text', 'Rot 90 CCW', ...
        'ButtonPushedFcn', @(~,~) callbacks.onRotateFlip('rot90ccw'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Rotate image 90° counter-clockwise');
    s.btnRotCCW.Layout.Row = 1; s.btnRotCCW.Layout.Column = 2;

    s.btnFlipH = uibutton(transformGL, 'Text', 'Flip H', ...
        'ButtonPushedFcn', @(~,~) callbacks.onRotateFlip('fliph'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Flip image horizontally (left-right mirror)');
    s.btnFlipH.Layout.Row = 2; s.btnFlipH.Layout.Column = 1;

    s.btnFlipV = uibutton(transformGL, 'Text', 'Flip V', ...
        'ButtonPushedFcn', @(~,~) callbacks.onRotateFlip('flipv'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Flip image vertically (top-bottom mirror)');
    s.btnFlipV.Layout.Row = 2; s.btnFlipV.Layout.Column = 2;

    s.btnZoomBox = uibutton(transformGL, 'Text', 'Zoom Box', ...
        'ButtonPushedFcn', callbacks.onZoomBox, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Draw a rectangle to zoom into a region (Esc to cancel)');
    s.btnZoomBox.Layout.Row = 3; s.btnZoomBox.Layout.Column = 1;

    s.btnResetZoom = uibutton(transformGL, 'Text', 'Reset Zoom', ...
        'ButtonPushedFcn', callbacks.onResetZoom, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Reset zoom to show the full image');
    s.btnResetZoom.Layout.Row = 3; s.btnResetZoom.Layout.Column = 2;

    s.btnCropImage = uibutton(transformGL, 'Text', 'Crop', ...
        'ButtonPushedFcn', callbacks.onCropImage, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Draw a rectangle to crop the image (destructive — use Undo Filters to revert)');
    s.btnCropImage.Layout.Row = 4; s.btnCropImage.Layout.Column = 1;

    s.btnSaveCrop = uibutton(transformGL, 'Text', 'Save Crop', ...
        'ButtonPushedFcn', @(~,~) callbacks.onExportAction('saveCrop'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Save a cropped region to file (draw box, then save)');
    s.btnSaveCrop.Layout.Row = 4; s.btnSaveCrop.Layout.Column = 2;

    s.btnBatchCrop = uibutton(transformGL, 'Text', 'Batch Crop', ...
        'ButtonPushedFcn', @(~,~) callbacks.onExportAction('batchCrop'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Define crop region, apply to all loaded images');
    s.btnBatchCrop.Layout.Row = 5; s.btnBatchCrop.Layout.Column = 1;

    s.btnBinImage = uibutton(transformGL, 'Text', 'Bin Image', ...
        'ButtonPushedFcn', callbacks.onBinImage, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Spatial binning (2x2, 4x4, 8x8) — sum or average mode');
    s.btnBinImage.Layout.Row = 5; s.btnBinImage.Layout.Column = 2;

    s.btnSetPixelSize = uibutton(transformGL, 'Text', 'Set Pixel Size', ...
        'ButtonPushedFcn', callbacks.onSetPixelSize, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Manually set or override pixel size calibration (nm/px, µm/px, etc.)');
    s.btnSetPixelSize.Layout.Row = 6; s.btnSetPixelSize.Layout.Column = [1 2];

    s.btnZoomDims = uibutton(transformGL, 'Text', 'Fixed Size Zoom', ...
        'ButtonPushedFcn', @(~,~) callbacks.onZoomBox([], [], 'dims'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Zoom to a user-specified width × height region (click to place, drag to move, Enter to confirm)');
    s.btnZoomDims.Layout.Row = 7; s.btnZoomDims.Layout.Column = [1 2];

    % ── Section 2: Filter ────────────────────────────────────────────────
    secFilter = localSection(sectionsCol, tk, 'Filter');
    filterGL = uigridlayout(secFilter.body, [6 2], ...
        'RowHeight', tabDef.RowHeight, 'ColumnWidth', tabDef.ColumnWidth, ...
        'Padding', tabDef.Padding, 'RowSpacing', tabDef.RowSpacing, ...
        'ColumnSpacing', tabDef.ColumnSpacing);

    s.btnGaussian = uibutton(filterGL, 'Text', 'Gaussian', ...
        'ButtonPushedFcn', callbacks.onGaussianFilter, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Apply Gaussian blur — prompts for sigma value');
    s.btnGaussian.Layout.Row = 1; s.btnGaussian.Layout.Column = 1;

    s.btnMedian = uibutton(filterGL, 'Text', 'Median', ...
        'ButtonPushedFcn', callbacks.onMedianFilter, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Apply median filter — prompts for window size (3/5/7)');
    s.btnMedian.Layout.Row = 1; s.btnMedian.Layout.Column = 2;

    s.btnCLAHE = uibutton(filterGL, 'Text', 'CLAHE', ...
        'ButtonPushedFcn', callbacks.onCLAHE, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Contrast-Limited Adaptive Histogram Equalization — prompts for tile size and clip limit');
    s.btnCLAHE.Layout.Row = 2; s.btnCLAHE.Layout.Column = 1;

    s.btnSharpen = uibutton(filterGL, 'Text', 'Sharpen', ...
        'ButtonPushedFcn', callbacks.onSharpen, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Unsharp mask sharpening — prompts for sigma and amount');
    s.btnSharpen.Layout.Row = 2; s.btnSharpen.Layout.Column = 2;

    s.btnMorphOp = uibutton(filterGL, 'Text', 'Morph Op', ...
        'ButtonPushedFcn', callbacks.onMorphOp, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Morphological operations (erode/dilate/open/close) on binary images');
    s.btnMorphOp.Layout.Row = 3; s.btnMorphOp.Layout.Column = 1;

    s.btnButterworth = uibutton(filterGL, 'Text', 'Butterworth', ...
        'ButtonPushedFcn', callbacks.onButterworth, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Butterworth bandpass filter — smooth frequency-domain filtering');
    s.btnButterworth.Layout.Row = 3; s.btnButterworth.Layout.Column = 2;

    s.btnFFTMask = uibutton(filterGL, 'Text', 'FFT Mask', ...
        'ButtonPushedFcn', callbacks.onFFTMask, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Draw masks on FFT to remove periodic noise; apply inverse FFT');
    s.btnFFTMask.Layout.Row = 4; s.btnFFTMask.Layout.Column = 1;

    s.btnLiveThresh = uibutton(filterGL, 'Text', 'Threshold', ...
        'ButtonPushedFcn', callbacks.onLiveThreshold, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Interactive threshold preview with live overlay; Otsu auto-threshold');
    s.btnLiveThresh.Layout.Row = 4; s.btnLiveThresh.Layout.Column = 2;

    s.btnMultiOtsu = uibutton(filterGL, 'Text', 'Multi-Thresh', ...
        'ButtonPushedFcn', callbacks.onMultiOtsu, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'N-class segmentation via multi-level Otsu threshold (2-5 classes)');
    s.btnMultiOtsu.Layout.Row = 5; s.btnMultiOtsu.Layout.Column = 1;

    s.btnUndoFilters = uibutton(filterGL, 'Text', 'Undo Filters', ...
        'ButtonPushedFcn', callbacks.onUndoFilters, ...
        'BackgroundColor', BTN_DANGER, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Revert to the original unfiltered image');
    s.btnUndoFilters.Layout.Row = 5; s.btnUndoFilters.Layout.Column = 2;

    s.cbPixelInspector = uicheckbox(filterGL, ...
        'Text', 'Pixel Inspector', 'Value', false, 'Enable', 'off', ...
        'ValueChangedFcn', callbacks.onPixelInspectorToggle, ...
        'Tooltip', 'Show NxN pixel neighborhood with intensity values near cursor');
    s.cbPixelInspector.Layout.Row = 6; s.cbPixelInspector.Layout.Column = [1 2];

    % ── Section 3: FFT & Analysis ────────────────────────────────────────
    secAnalysis = localSection(sectionsCol, tk, 'FFT & Analysis');
    analysisGL = uigridlayout(secAnalysis.body, [6 2], ...
        'RowHeight', tabDef.RowHeight, 'ColumnWidth', tabDef.ColumnWidth, ...
        'Padding', tabDef.Padding, 'RowSpacing', tabDef.RowSpacing, ...
        'ColumnSpacing', tabDef.ColumnSpacing);

    s.btnShowFFT = uibutton(analysisGL, 'Text', 'Show FFT', ...
        'ButtonPushedFcn', callbacks.onShowFFT, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Display 2D FFT magnitude in a new figure window');
    s.btnShowFFT.Layout.Row = 1; s.btnShowFFT.Layout.Column = 1;

    s.btnLiveFFT = uibutton(analysisGL, 'state', 'Text', 'Live FFT', ...
        'ValueChangedFcn', callbacks.onLiveFFTToggle, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Show persistent FFT panel that updates with filters');
    s.btnLiveFFT.Layout.Row = 1; s.btnLiveFFT.Layout.Column = 2;

    s.btnRadialProfile = uibutton(analysisGL, 'Text', 'Radial Profile', ...
        'ButtonPushedFcn', callbacks.onRadialProfile, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Compute radial average/max profile from FFT or diffraction pattern');
    s.btnRadialProfile.Layout.Row = 2; s.btnRadialProfile.Layout.Column = 1;

    s.btnAzIntegrate = uibutton(analysisGL, 'Text', 'Az Integrate', ...
        'ButtonPushedFcn', callbacks.onAzIntegrate, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Full azimuthal integration of 2D pattern → 1D powder pattern');
    s.btnAzIntegrate.Layout.Row = 2; s.btnAzIntegrate.Layout.Column = 2;

    s.btnLatticeMeasure = uibutton(analysisGL, 'Text', 'Lattice', ...
        'ButtonPushedFcn', @(~,~) callbacks.onDiffractionAction('latticeMeasure'), ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', ['Click two FFT spots to measure lattice parameters. ' ...
                    'Reports a, b, ' char(947) ', d-spacings, and overlays unit cell.']);
    s.btnLatticeMeasure.Layout.Row = 3; s.btnLatticeMeasure.Layout.Column = 1;

    s.btnGPA = uibutton(analysisGL, 'Text', 'GPA Strain', ...
        'ButtonPushedFcn', callbacks.onGPA, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Geometric Phase Analysis: compute 2D strain maps from HRTEM lattice images');
    s.btnGPA.Layout.Row = 3; s.btnGPA.Layout.Column = 2;

    s.btnCTF = uibutton(analysisGL, 'Text', 'CTF Estimate', ...
        'ButtonPushedFcn', callbacks.onCTFEstimate, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Estimate defocus from Thon rings in the power spectrum (TEM/cryo-EM)');
    s.btnCTF.Layout.Row = 4; s.btnCTF.Layout.Column = 1;

    s.btnNoiseEstimate = uibutton(analysisGL, 'Text', 'Noise Est.', ...
        'ButtonPushedFcn', callbacks.onNoiseEstimate, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Characterize image noise and suggest optimal filter parameters');
    s.btnNoiseEstimate.Layout.Row = 4; s.btnNoiseEstimate.Layout.Column = 2;

    s.btnTemplateMatch = uibutton(analysisGL, 'Text', 'Template Match', ...
        'ButtonPushedFcn', callbacks.onTemplateMatch, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Find repeated features by selecting a template region');
    s.btnTemplateMatch.Layout.Row = 5; s.btnTemplateMatch.Layout.Column = 1;

    s.btnInterfaceFit = uibutton(analysisGL, 'Text', 'Interface Fit', ...
        'ButtonPushedFcn', callbacks.onInterfaceFit, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Fit erf/sigmoid to a line profile for interface width measurement (10-90%)');
    s.btnInterfaceFit.Layout.Row = 6; s.btnInterfaceFit.Layout.Column = 1;

    s.btnDefectCount = uibutton(analysisGL, 'Text', 'Defect Count', ...
        'ButtonPushedFcn', callbacks.onDefectCount, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Estimate dislocation density via stereological line intersection counting');
    s.btnDefectCount.Layout.Row = 6; s.btnDefectCount.Layout.Column = 2;

    % ── Section 4: Surface & Stack ───────────────────────────────────────
    secSurface = localSection(sectionsCol, tk, 'Surface & Stack');
    surfaceGL = uigridlayout(secSurface.body, [6 2], ...
        'RowHeight', tabDef.RowHeight, 'ColumnWidth', tabDef.ColumnWidth, ...
        'Padding', tabDef.Padding, 'RowSpacing', tabDef.RowSpacing, ...
        'ColumnSpacing', tabDef.ColumnSpacing);

    s.btnPlaneLevel = uibutton(surfaceGL, 'Text', 'Plane Level', ...
        'ButtonPushedFcn', callbacks.onPlaneLevel, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Subtract a best-fit polynomial surface (1st/2nd/3rd order) for AFM/SPM leveling');
    s.btnPlaneLevel.Layout.Row = 1; s.btnPlaneLevel.Layout.Column = 1;

    s.btnRoughness = uibutton(surfaceGL, 'Text', 'Roughness', ...
        'ButtonPushedFcn', callbacks.onRoughness, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Compute surface roughness: Ra, Rq, Rz, skewness, kurtosis, bearing ratio');
    s.btnRoughness.Layout.Row = 1; s.btnRoughness.Layout.Column = 2;

    s.btn3DSurface = uibutton(surfaceGL, 'Text', '3D Surface', ...
        'ButtonPushedFcn', callbacks.on3DSurface, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Render image as 3D height map (AFM/STM/topography)');
    s.btn3DSurface.Layout.Row = 2; s.btn3DSurface.Layout.Column = 1;

    s.btnSurfacePlot = uibutton(surfaceGL, 'Text', 'Surface Plot', ...
        'ButtonPushedFcn', callbacks.onSurfacePlot, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Render image intensity as a 3D surface plot in a new figure');
    s.btnSurfacePlot.Layout.Row = 2; s.btnSurfacePlot.Layout.Column = 2;

    s.btnBackProject = uibutton(surfaceGL, 'Text', 'Back-Project', ...
        'ButtonPushedFcn', callbacks.onBackProject, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Filtered back-projection preview from a tilt-series sinogram');
    s.btnBackProject.Layout.Row = 3; s.btnBackProject.Layout.Column = 1;

    s.btnParticles = uibutton(surfaceGL, 'Text', 'Particles', ...
        'ButtonPushedFcn', callbacks.onParticleCount, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Threshold + count particles; show size distribution');
    s.btnParticles.Layout.Row = 3; s.btnParticles.Layout.Column = 2;

    s.btnWatershed = uibutton(surfaceGL, 'Text', 'Watershed', ...
        'ButtonPushedFcn', callbacks.onWatershed, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Watershed segmentation to split touching particles (no toolbox)');
    s.btnWatershed.Layout.Row = 4; s.btnWatershed.Layout.Column = 1;

    s.btnAlignStack = uibutton(surfaceGL, 'Text', 'Align Stack', ...
        'ButtonPushedFcn', callbacks.onAlignStack, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Cross-correlation drift correction for loaded image stack');
    s.btnAlignStack.Layout.Row = 4; s.btnAlignStack.Layout.Column = 2;

    s.btnStitchImages = uibutton(surfaceGL, 'Text', 'Stitch', ...
        'ButtonPushedFcn', callbacks.onStitchImages, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Stitch overlapping images into a panoramic mosaic');
    s.btnStitchImages.Layout.Row = 5; s.btnStitchImages.Layout.Column = 1;

    s.btnMontage = uibutton(surfaceGL, 'Text', 'Montage / Stitch', ...
        'ButtonPushedFcn', callbacks.onMontage, ...
        'BackgroundColor', BTN_TOOL, 'FontColor', BTN_FG, 'Enable', 'off', ...
        'Tooltip', 'Grid-based tiled image stitching with overlap cross-correlation');
    s.btnMontage.Layout.Row = 5; s.btnMontage.Layout.Column = 2;

    % Per-section grids exposed for theming (see setTheme in FermiViewer.m).
    % Name kept as processTabGrids for call-site compatibility.
    s.processTabGrids  = {transformGL, filterGL, analysisGL, surfaceGL};
    s.processInnerGL   = processInnerGL;
end

% ════════════════════════════════════════════════════════════════════════
%  Collapsible-section helpers (Variant A right panel)
% ════════════════════════════════════════════════════════════════════════
function sec = localSection(parent, tk, titleText)
%LOCALSECTION  A collapsible section: clickable header + content body grid.
%   Uses fermiViewer.chrome.sectionHeader so these sections match the look
%   of the panel's other collapsible sections (Contrast / Measurement /
%   Annotations / Export) exactly — one source of truth for header styling.
    sec.outerGL = uigridlayout(parent, [2 1], 'RowHeight', {26, 'fit'}, ...
        'ColumnWidth', {'1x'}, 'Padding', [0 0 0 0], 'RowSpacing', 0);
    sec.header = fermiViewer.chrome.sectionHeader(sec.outerGL, ...
        [char(9660) '  ' titleText], ...                  % ▼ + Title
        @(~,~) localToggleSection(sec.outerGL, sec.header), ...
        'Theme', tk.theme);
    sec.header.Layout.Row = 1;
    sec.body = uigridlayout(sec.outerGL, [1 1], 'ColumnWidth', {'1x'}, ...
        'RowHeight', {'fit'}, 'Padding', [0 0 0 0]);
    sec.body.Layout.Row = 2;
end

function localToggleSection(outerGL, header)
%LOCALTOGGLESECTION  Collapse/expand by flipping the body row height.
    if isequal(outerGL.RowHeight{2}, 0)
        outerGL.RowHeight = {26, 'fit'};
        header.Text = strrep(header.Text, char(9654), char(9660));  % ▶ → ▼
    else
        outerGL.RowHeight = {26, 0};
        header.Text = strrep(header.Text, char(9660), char(9654));  % ▼ → ▶
    end
end
