function s = buildContrastPanel(parent, tk, palette, callbacks)
%BUILDCONTRASTPANEL  Construct the Contrast/Display sub-panel for FermiViewer.
%
% Syntax
%   s = emViewer.buildContrastPanel(parent, tk, palette, callbacks)
%
% Inputs
%   parent     uigridlayout (toolsGL) — pnlContrast is created here and
%              assigned Layout.Row = 2 by the caller.
%   tk         UX tokens struct (unused here, reserved for future theming)
%   palette    struct of semantic button colours:
%                .tool  — gray, secondary tools
%                .fg    — white foreground text
%   callbacks  struct of function handles:
%                .onContrastChanged        — slider lo/hi changed
%                .onContrastEditChanged    — edit-field typed value changed
%                .onAutoContrast           — Auto button
%                .onResetContrast          — Reset button
%                .onColormapChanged        — colormap dropdown changed
%                .onColorbarToggle         — Show Colorbar checkbox
%                .onGammaChanged           — gamma slider changed
%                .onMinimapToggle          — Show Minimap checkbox
%                .onContrastTransformChanged — transform dropdown changed
%                .onInvertToggle           — Invert checkbox
%
% Outputs
%   s   struct of widget handles for all interactive widgets:
%         .pnlContrast           — outer uipanel (parented to toolsGL)
%         .sldLow                — low-contrast slider
%         .efLow                 — low-contrast edit field
%         .sldHigh               — high-contrast slider
%         .efHigh                — high-contrast edit field
%         .sldGamma              — gamma slider
%         .efGamma               — gamma edit field
%         .ddColormap            — colormap dropdown
%         .cbColorbar            — Show Colorbar checkbox
%         .cbMinimap             — Show Minimap checkbox
%         .ddContrastTransform   — display transform dropdown
%         .cbInvert              — Invert checkbox
%         .ddRenderMode          — render quality dropdown
%         .hColorbar             — colorbar axes handle (initially [])
%         .hMinimap              — minimap axes handle (initially [])
%         .hMinimapRect          — viewport rect on minimap (initially [])
%
% Examples
%   cbs = struct( ...
%       'onContrastChanged',        @onContrastChanged, ...
%       'onContrastEditChanged',    @onContrastEditChanged, ...
%       'onAutoContrast',           @onAutoContrast, ...
%       'onResetContrast',          @onResetContrast, ...
%       'onColormapChanged',        @onColormapChanged, ...
%       'onColorbarToggle',         @onColorbarToggle, ...
%       'onGammaChanged',           @onGammaChanged, ...
%       'onMinimapToggle',          @onMinimapToggle, ...
%       'onContrastTransformChanged', @onContrastTransformChanged, ...
%       'onInvertToggle',           @onInvertToggle);
%   contrast_ = emViewer.buildContrastPanel(toolsGL, tk, palette, cbs);
%   contrast_.pnlContrast.Layout.Row = 2;

    arguments
        parent
        tk         struct  %#ok<INUSA>  % reserved for future theming
        palette    struct
        callbacks  struct
    end

    % Palette shorthands
    BTN_TOOL = palette.tool;
    BTN_FG   = palette.fg;

    % ── Outer panel (parented to toolsGL, row assigned by caller) ────────
    s.pnlContrast = uipanel(parent, 'BorderType', 'line');

    % Inner grid: Low label+edit on row 1, Low slider on row 2, High on
    % 3-4, Gamma on 9-10. Label rows are 20 px tall so they can host a
    % small uieditfield next to the label for typed numeric entry.
    s.contrastInnerGL = uigridlayout(s.pnlContrast, [13 2], ...
        'RowHeight',   {20, 20, 20, 20, 2, 20, 20, 18, 20, 20, 18, 20, 18}, ...
        'ColumnWidth', {'1x', '1x'}, ...
        'Padding',     [3 2 3 2], ...
        'RowSpacing',  1, ...
        'ColumnSpacing', 3);

    % ── Row 1: Low label + edit field ────────────────────────────────────
    lblLow = uilabel(s.contrastInnerGL, 'Text', 'Low', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    lblLow.Layout.Row = 1; lblLow.Layout.Column = 1;

    s.efLow = uieditfield(s.contrastInnerGL, 'numeric', ...
        'Value', 0, 'FontSize', 11, ...
        'ValueDisplayFormat', '%.4g', ...
        'ValueChangedFcn', callbacks.onContrastEditChanged, ...
        'Tooltip', 'Type exact low-contrast value (matches slider)');
    s.efLow.Layout.Row = 1; s.efLow.Layout.Column = 2;

    % ── Row 2: Low slider ────────────────────────────────────────────────
    s.sldLow = uislider(s.contrastInnerGL, ...
        'Value', 0, 'Limits', [0 1], ...
        'ValueChangedFcn', callbacks.onContrastChanged, ...
        'Tooltip', 'Lower contrast bound (dark clipping point)');
    s.sldLow.Layout.Row = 2; s.sldLow.Layout.Column = [1 2];
    s.sldLow.MajorTicks = [];
    s.sldLow.MinorTicks = [];

    % ── Row 3: High label + edit field ───────────────────────────────────
    lblHigh = uilabel(s.contrastInnerGL, 'Text', 'High', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    lblHigh.Layout.Row = 3; lblHigh.Layout.Column = 1;

    s.efHigh = uieditfield(s.contrastInnerGL, 'numeric', ...
        'Value', 1, 'FontSize', 11, ...
        'ValueDisplayFormat', '%.4g', ...
        'ValueChangedFcn', callbacks.onContrastEditChanged, ...
        'Tooltip', 'Type exact high-contrast value (matches slider)');
    s.efHigh.Layout.Row = 3; s.efHigh.Layout.Column = 2;

    % ── Row 4: High slider ───────────────────────────────────────────────
    s.sldHigh = uislider(s.contrastInnerGL, ...
        'Value', 1, 'Limits', [0 1], ...
        'ValueChangedFcn', callbacks.onContrastChanged, ...
        'Tooltip', 'Upper contrast bound (bright clipping point)');
    s.sldHigh.Layout.Row = 4; s.sldHigh.Layout.Column = [1 2];
    s.sldHigh.MajorTicks = [];
    s.sldHigh.MinorTicks = [];

    % Row 5 is a spacing gap

    % ── Row 6: Auto + Reset buttons ──────────────────────────────────────
    btnAutoContrast = uibutton(s.contrastInnerGL, 'Text', 'Auto', ...
        'ButtonPushedFcn', callbacks.onAutoContrast, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Auto-stretch contrast to [2nd, 98th] percentile');
    btnAutoContrast.Layout.Row = 6; btnAutoContrast.Layout.Column = 1;

    btnResetContrast = uibutton(s.contrastInnerGL, 'Text', 'Reset', ...
        'ButtonPushedFcn', callbacks.onResetContrast, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Reset contrast to full pixel range AND gamma to 1.0');
    btnResetContrast.Layout.Row = 6; btnResetContrast.Layout.Column = 2;

    % ── Row 7: Colormap dropdown ──────────────────────────────────────────
    s.ddColormap = uidropdown(s.contrastInnerGL, ...
        'Items', {'gray', 'parula', 'hot', 'jet', 'bone'}, ...
        'Value', 'gray', ...
        'ValueChangedFcn', callbacks.onColormapChanged, ...
        'Tooltip', 'Select colormap for image display');
    s.ddColormap.Layout.Row = 7; s.ddColormap.Layout.Column = [1 2];

    % ── Row 8: Show Colorbar checkbox ────────────────────────────────────
    s.cbColorbar = uicheckbox(s.contrastInnerGL, ...
        'Text',    'Show Colorbar', ...
        'Value',   false, ...
        'Enable',  'off', ...
        'ValueChangedFcn', callbacks.onColorbarToggle, ...
        'Tooltip', 'Show/hide a colorbar next to the image');
    s.cbColorbar.Layout.Row = 8; s.cbColorbar.Layout.Column = [1 2];

    % Dynamic colorbar handle (created/deleted at runtime)
    s.hColorbar = [];

    % ── Row 9: Gamma label + edit field ──────────────────────────────────
    s.lblGamma = uilabel(s.contrastInnerGL, 'Text', 'Gamma', ...
        'FontSize', 11, 'HorizontalAlignment', 'left');
    s.lblGamma.Layout.Row = 9; s.lblGamma.Layout.Column = 1;

    s.efGamma = uieditfield(s.contrastInnerGL, 'numeric', ...
        'Value', 1, 'FontSize', 11, ...
        'Limits', [0.1 5.0], ...
        'ValueDisplayFormat', '%.2f', ...
        'ValueChangedFcn', callbacks.onContrastEditChanged, ...
        'Tooltip', 'Type exact gamma value (1.0 = linear; Reset button restores 1.0)');
    s.efGamma.Layout.Row = 9; s.efGamma.Layout.Column = 2;

    % ── Row 10: Gamma slider ──────────────────────────────────────────────
    s.sldGamma = uislider(s.contrastInnerGL, ...
        'Value', 1, 'Limits', [0.1 5.0], ...
        'ValueChangedFcn', callbacks.onGammaChanged, ...
        'Tooltip', 'Non-linear intensity mapping (1.0 = linear, <1 = brighten darks, >1 = darken)');
    s.sldGamma.Layout.Row = 10; s.sldGamma.Layout.Column = [1 2];
    s.sldGamma.MajorTicks = [0.1 1.0 2.0 3.0 5.0];
    s.sldGamma.MinorTicks = [];

    % ── Row 11: Show Minimap checkbox ────────────────────────────────────
    s.cbMinimap = uicheckbox(s.contrastInnerGL, ...
        'Text',    'Show Minimap', ...
        'Value',   false, ...
        'Enable',  'off', ...
        'ValueChangedFcn', callbacks.onMinimapToggle, ...
        'Tooltip', 'Show overview inset with zoomed viewport rectangle');
    s.cbMinimap.Layout.Row = 11; s.cbMinimap.Layout.Column = [1 2];

    % ── Row 12: Contrast transform dropdown ──────────────────────────────
    s.ddContrastTransform = uidropdown(s.contrastInnerGL, ...
        'Items', {'linear', 'log', 'sqrt', 'power'}, ...
        'Value', 'linear', ...
        'ValueChangedFcn', callbacks.onContrastTransformChanged, ...
        'Tooltip', 'Display transform applied before contrast window (log for FFT/diffraction)');
    s.ddContrastTransform.Layout.Row = 12; s.ddContrastTransform.Layout.Column = [1 2];

    % ── Row 13: Invert checkbox (col 1) + render-mode dropdown (col 2) ───
    s.cbInvert = uicheckbox(s.contrastInnerGL, ...
        'Text',    'Invert', ...
        'Value',   false, ...
        'ValueChangedFcn', callbacks.onInvertToggle, ...
        'Tooltip', 'Invert image contrast (bright-field / dark-field toggle)');
    s.cbInvert.Layout.Row = 13; s.cbInvert.Layout.Column = 1;

    % Render quality selector. 'HQ' = DM-style area-averaged downsample
    % (preserves atomic detail when image > axes size). 'Fast' skips the
    % downsample step and renders the full-resolution buffer with
    % nearest-neighbor — use this if the HQ path is slow on very large
    % images or when exact per-pixel inspection is needed.
    s.ddRenderMode = uidropdown(s.contrastInnerGL, ...
        'Items',     {'HQ', 'Fast'}, ...
        'ItemsData', {'hq', 'fast'}, ...
        'Value',     'hq', ...
        'ValueChangedFcn', callbacks.onContrastEditChanged, ...
        'Tooltip',   'HQ = DM-style area-averaged downsample; Fast = raw pixels + nearest-neighbor');
    s.ddRenderMode.Layout.Row = 13; s.ddRenderMode.Layout.Column = 2;

    % Dynamic minimap handles (created/deleted at runtime)
    s.hMinimap     = [];
    s.hMinimapRect = [];
end
