function s = buildExportPanel(parent, palette, callbacks)
%BUILDEXPORTPANEL  Build the Export & Style inner grid for FermiViewer.
%
% Syntax
%   s = emViewer.buildExportPanel(parent, palette, callbacks)
%
% Inputs
%   parent     uigridlayout that is exportInnerGL in FermiViewer.m
%              (14 rows x 2 cols, already created by the caller)
%   palette    struct of button-color scalars matching FermiViewer.m:
%                .export   — slate export-action color
%                .tool     — gray secondary-tool color
%                .fg       — white foreground for dark buttons
%   callbacks  struct of function handles, one per interactive widget:
%                .onSaveImage, .onCopyClipboard,
%                .onExportWithOverlays, .onBatchExport,
%                .onSessionSave, .onSessionLoad,
%                .onFigureBuilder, .onJournalExport,
%                .onPubPresets, .onCalibratedColorbar,
%                .onCustomColormap, .onColormapPreset,
%                .onCreateGIF, .onBatchConvert,
%                .onColorOverlay, .onFlickerCompare,
%                .onMacroToggle, .onImageMath,
%                .onBatchRename, .onRenameSelected
%
% Output
%   s          struct of all created widget handles.  Every handle that
%              FermiViewer.m references after the call site is included.
%              Fields:
%                .btnSaveImage, .btnCopyClipboard,
%                .btnExportOverlays, .btnBatchExport,
%                .btnSessionSave, .btnSessionLoad,
%                .lblDPI, .ddExportDPI,
%                .lblPubHeader,
%                .btnFigureBuilder, .btnJournalExport,
%                .btnPubPresets, .btnCalibColorbar,
%                .btnCustomCmap, .btnColormapPreset,
%                .btnCreateGIF, .btnBatchConvert,
%                .lblUtilHeader,
%                .btnColorOverlay, .btnFlickerCompare,
%                .btnMacroRecord, .btnImgMath,
%                .lblRename, .efRenameBase,
%                .btnBatchRename, .btnRenameSelected

    arguments
        parent
        palette    struct
        callbacks  struct
    end

    % ---- Tier 1: Core Export (rows 1-4) ----
    % Row 1: Save / Copy
    s.btnSaveImage = uibutton(parent, 'Text', 'Save Image', ...
        'ButtonPushedFcn', callbacks.onSaveImage, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Save current processed image to PNG or TIFF');
    s.btnSaveImage.Layout.Row = 1; s.btnSaveImage.Layout.Column = 1;

    s.btnCopyClipboard = uibutton(parent, 'Text', 'Copy', ...
        'ButtonPushedFcn', callbacks.onCopyClipboard, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Copy current view to clipboard');
    s.btnCopyClipboard.Layout.Row = 1; s.btnCopyClipboard.Layout.Column = 2;

    % Row 2: Burn Overlays / Batch Export
    s.btnExportOverlays = uibutton(parent, 'Text', 'Burn Overlays', ...
        'ButtonPushedFcn', callbacks.onExportWithOverlays, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Save with overlays burned in (scale bar, annotations, measurements)');
    s.btnExportOverlays.Layout.Row = 2; s.btnExportOverlays.Layout.Column = 1;

    s.btnBatchExport = uibutton(parent, 'Text', 'Batch Export', ...
        'ButtonPushedFcn', callbacks.onBatchExport, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Export all loaded images with current contrast to a folder');
    s.btnBatchExport.Layout.Row = 2; s.btnBatchExport.Layout.Column = 2;

    % Row 3: Session Save / Load
    s.btnSessionSave = uibutton(parent, 'Text', 'Save .mat', ...
        'ButtonPushedFcn', callbacks.onSessionSave, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Save images, contrast, overlays, annotations to .mat session');
    s.btnSessionSave.Layout.Row = 3; s.btnSessionSave.Layout.Column = 1;

    s.btnSessionLoad = uibutton(parent, 'Text', 'Load .mat', ...
        'ButtonPushedFcn', callbacks.onSessionLoad, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, ...
        'Tooltip', 'Restore a previously saved session');
    s.btnSessionLoad.Layout.Row = 3; s.btnSessionLoad.Layout.Column = 2;

    % Row 4: DPI
    s.lblDPI = uilabel(parent, 'Text', 'DPI:', 'FontSize', 11);
    s.lblDPI.Layout.Row = 4; s.lblDPI.Layout.Column = 1;

    s.ddExportDPI = uidropdown(parent, ...
        'Items',     {'72', '150', '300', '600'}, ...
        'ItemsData', [72, 150, 300, 600], ...
        'Value',     300, ...
        'Tooltip',   'DPI for overlay and clipboard exports');
    s.ddExportDPI.Layout.Row = 4; s.ddExportDPI.Layout.Column = 2;

    % ---- Tier 2: Publication (rows 5-9) ----
    % Row 5: Sub-header
    s.lblPubHeader = uilabel(parent, 'Text', 'Publication', ...
        'FontWeight', 'bold', 'FontSize', 11, ...
        'FontColor', [0.35 0.35 0.35]);
    s.lblPubHeader.Layout.Row = 5; s.lblPubHeader.Layout.Column = [1 2];

    % Row 6: Figure Builder / Journal Export
    s.btnFigureBuilder = uibutton(parent, 'Text', 'Figure Builder', ...
        'ButtonPushedFcn', callbacks.onFigureBuilder, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Build multi-panel publication figure with labels, scale bars, and uniform sizing');
    s.btnFigureBuilder.Layout.Row = 6; s.btnFigureBuilder.Layout.Column = 1;

    s.btnJournalExport = uibutton(parent, 'Text', 'Journal Export', ...
        'ButtonPushedFcn', callbacks.onJournalExport, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Export with journal-specific presets (Nature, Science, ACS, Elsevier)');
    s.btnJournalExport.Layout.Row = 6; s.btnJournalExport.Layout.Column = 2;

    % Row 7: Pub Presets / Calib. Colorbar
    s.btnPubPresets = uibutton(parent, 'Text', 'Pub Presets', ...
        'ButtonPushedFcn', callbacks.onPubPresets, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Apply journal-specific annotation formatting (APS/Nature/ACS)');
    s.btnPubPresets.Layout.Row = 7; s.btnPubPresets.Layout.Column = 1;

    s.btnCalibColorbar = uibutton(parent, 'Text', 'Calibrate Colorbar', ...
        'ButtonPushedFcn', callbacks.onCalibratedColorbar, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Add a calibrated colorbar with real-unit labels burned into exports');
    s.btnCalibColorbar.Layout.Row = 7; s.btnCalibColorbar.Layout.Column = 2;

    % Row 8: Custom Colormap / EM Colormaps
    s.btnCustomCmap = uibutton(parent, 'Text', 'Custom Colormap', ...
        'ButtonPushedFcn', callbacks.onCustomColormap, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Create a custom colormap from user-defined color stops');
    s.btnCustomCmap.Layout.Row = 8; s.btnCustomCmap.Layout.Column = 1;

    s.btnColormapPreset = uibutton(parent, 'Text', 'EM Colormaps', ...
        'ButtonPushedFcn', callbacks.onColormapPreset, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Auto-select colormap based on EM mode (SEM/TEM/STEM/EDS/phase)');
    s.btnColormapPreset.Layout.Row = 8; s.btnColormapPreset.Layout.Column = 2;

    % Row 9: Create GIF / Batch Convert
    s.btnCreateGIF = uibutton(parent, 'Text', 'Create GIF', ...
        'ButtonPushedFcn', callbacks.onCreateGIF, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Combine selected images into an animated GIF with optional scale bar');
    s.btnCreateGIF.Layout.Row = 9; s.btnCreateGIF.Layout.Column = 1;

    s.btnBatchConvert = uibutton(parent, 'Text', 'Batch Convert', ...
        'ButtonPushedFcn', callbacks.onBatchConvert, ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Convert loaded images between formats (PNG/TIFF/JPEG)');
    s.btnBatchConvert.Layout.Row = 9; s.btnBatchConvert.Layout.Column = 2;

    % ---- Tier 3: Utilities (rows 10-14) ----
    % Row 10: Sub-header
    s.lblUtilHeader = uilabel(parent, 'Text', 'Utilities', ...
        'FontWeight', 'bold', 'FontSize', 11, ...
        'FontColor', [0.35 0.35 0.35]);
    s.lblUtilHeader.Layout.Row = 10; s.lblUtilHeader.Layout.Column = [1 2];

    % Row 11: Overlay / Flicker
    s.btnColorOverlay = uibutton(parent, 'Text', 'Overlay', ...
        'ButtonPushedFcn', callbacks.onColorOverlay, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Blend two images with different colormaps in a new figure');
    s.btnColorOverlay.Layout.Row = 11; s.btnColorOverlay.Layout.Column = 1;

    s.btnFlickerCompare = uibutton(parent, 'Text', 'Flicker', ...
        'ButtonPushedFcn', callbacks.onFlickerCompare, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Rapidly alternate between two images to spot subtle differences');
    s.btnFlickerCompare.Layout.Row = 11; s.btnFlickerCompare.Layout.Column = 2;

    % Row 12: Record Macro / Img Math
    s.btnMacroRecord = uibutton(parent, 'Text', 'Record Macro', ...
        'ButtonPushedFcn', callbacks.onMacroToggle, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Record measurement operations as a replayable macro');
    s.btnMacroRecord.Layout.Row = 12; s.btnMacroRecord.Layout.Column = 1;

    s.btnImgMath = uibutton(parent, 'Text', 'Img Math', ...
        'ButtonPushedFcn', callbacks.onImageMath, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Image arithmetic: subtract, divide, or ratio two loaded images');
    s.btnImgMath.Layout.Row = 12; s.btnImgMath.Layout.Column = 2;

    % Row 13: Rename header + base name field
    s.lblRename = uilabel(parent, 'Text', 'Rename', ...
        'FontWeight', 'bold', 'FontSize', 11, ...
        'FontColor', [0.15 0.15 0.15]);
    s.lblRename.Layout.Row = 13; s.lblRename.Layout.Column = 1;

    s.efRenameBase = uieditfield(parent, 'text', ...
        'Placeholder', 'base_name', ...
        'Tooltip', 'Base name for rename — files become name_001, _002, etc.');
    s.efRenameBase.Layout.Row = 13; s.efRenameBase.Layout.Column = 2;

    % Row 14: Rename All / Selected
    s.btnBatchRename = uibutton(parent, 'Text', 'Rename All', ...
        'ButtonPushedFcn', callbacks.onBatchRename, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Rename all loaded files: base_001, _002, etc.');
    s.btnBatchRename.Layout.Row = 14; s.btnBatchRename.Layout.Column = 1;

    s.btnRenameSelected = uibutton(parent, 'Text', 'Rename Sel.', ...
        'ButtonPushedFcn', callbacks.onRenameSelected, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, 'Enable', 'off', ...
        'Tooltip', 'Rename only selected file(s) with sequential numbering');
    s.btnRenameSelected.Layout.Row = 14; s.btnRenameSelected.Layout.Column = 2;
end
