function s = buildToolbar(parent, tk, palette, callbacks)
%BUILDTOOLBAR  Construct the main toolbar row for FermiViewer.
%
% Syntax
%   s = fermiViewer.buildToolbar(parent, tk, palette, callbacks)
%
% Inputs
%   parent    — uigridlayout that owns row 1 (the toolbar row)
%   tk        — fermiViewer.chrome.uxTokens(theme) token struct (or [] →
%               defaults to dark). Used for the accent Open button and the
%               1-px hairline group separators (Variant A redesign).
%   palette   — struct from fermiViewer.chrome.buttonPalette() with fields:
%                 .primary, .danger, .tool, .fg
%   callbacks — struct of nested-function handles:
%                 .onOpenFiles, .onRecentFileSelected, .onRemoveImage,
%                 .onZoomFit, .onZoomActual, .onZoomOut, .onCompareToggle,
%                 .onThumbnailGrid, .onEDSToolbarToggle, .onPreferences,
%                 .onThemeToggle, .onShowEMShortcuts
%
% Outputs
%   s — struct with fields:
%         .toolbarGL      — the toolbar uigridlayout (1×13)
%         .lblFilename    — uilabel showing the current filename
%         .ddRecent       — uidropdown of recent files
%         .btnCompare     — state button for Compare mode
%         .btnGrid        — button for thumbnail grid (enabled when ≥2 images)
%         .btnEDSToolbar  — state button for EDS composite mode
%
% Notes
%   The zoom-out button uses an icon from icons/fermiviewer/zoomOut.png.
%   If the file is missing the button still renders with empty text (no error).
%   btnShortcuts is intentionally not stored in s — it has no downstream
%   enable/disable logic.

    if isempty(tk) || ~isstruct(tk)
        tk = fermiViewer.chrome.uxTokens('dark');
    end
    BTN_OPEN    = tk.color.accent;   % redesign: primary action = accent blue
    BTN_DANGER  = palette.danger;
    BTN_TOOL    = palette.tool;
    BTN_FG      = palette.fg;
    SEP_COLOR   = tk.color.borderSoft;

    % ── Toolbar grid ───────────────────────────────────────────────────────
    % 17 columns — Variant A: 5 widget groups split by 1-px hairline columns.
    %   1(80) Open · 2(120) Recent          [File]
    %   3(1)  sep
    %   4(55) Remove                          [Edit]
    %   5(1)  sep
    %   6(35) Fit · 7(35) 1:1 · 8(28) ZoomOut [Zoom]
    %   9(1)  sep
    %   10(60) Compare · 11(35) Grid · 12(35) EDS  [Modes]
    %   13(1x) Filename
    %   14(1) sep
    %   15(32) Prefs · 16(32) Theme · 17(28) ?     [System]
    toolbarGL = uigridlayout(parent, [1 16], ...
        'ColumnWidth', {80, 120, 1, 55, 1, 35, 35, 1, 60, 35, 35, '1x', 1, 32, 32, 28}, ...
        'RowHeight',   {'1x'}, ...
        'Padding',     [4 2 4 2], ...
        'ColumnSpacing', 5);
    toolbarGL.Layout.Row    = 1;
    toolbarGL.Layout.Column = 1;

    % Hairline group separators (1-px borderless panels read as dividers).
    for sepCol = [3, 5, 8, 13]
        sep = uipanel(toolbarGL, 'BorderType', 'none', 'BackgroundColor', SEP_COLOR);
        sep.Layout.Row = 1; sep.Layout.Column = sepCol;
    end

    % ── Widgets ────────────────────────────────────────────────────────────
    btnOpen = uibutton(toolbarGL, 'Text', 'Open', ...
        'ButtonPushedFcn', callbacks.onOpenFiles, ...
        'BackgroundColor', BTN_OPEN, ...
        'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Tooltip', 'Browse for TIFF or RAW image files to load');
    btnOpen.Layout.Row = 1; btnOpen.Layout.Column = 1;
    ddRecent = uidropdown(toolbarGL, ...
        'Items', {'(recent files)'}, ...
        'Value', '(recent files)', ...
        'ValueChangedFcn', callbacks.onRecentFileSelected, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Open a recently loaded file');
    ddRecent.Layout.Row = 1; ddRecent.Layout.Column = 2;

    btnRemove = uibutton(toolbarGL, 'Text', 'Remove', ...
        'ButtonPushedFcn', callbacks.onRemoveImage, ...
        'BackgroundColor', BTN_DANGER, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Remove the selected image(s) from the list');
    btnRemove.Layout.Row = 1; btnRemove.Layout.Column = 4;
    btnZoomFit = uibutton(toolbarGL, 'Text', 'Fit', ...
        'ButtonPushedFcn', callbacks.onZoomFit, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Zoom to fit the entire image in the axes');
    btnZoomFit.Layout.Row = 1; btnZoomFit.Layout.Column = 6;
    btnZoomActual = uibutton(toolbarGL, 'Text', '1:1', ...
        'ButtonPushedFcn', callbacks.onZoomActual, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Zoom to actual pixels (100% — one image pixel = one screen pixel)');
    btnZoomActual.Layout.Row = 1; btnZoomActual.Layout.Column = 7;
    % (Zoom-out moved to the in-axes image toolbar, next to the zoom tool.)
    btnCompare = uibutton(toolbarGL, 'state', 'Text', 'Compare', ...
        'ValueChangedFcn', callbacks.onCompareToggle, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Side-by-side comparison (Tab to switch active panel, arrows to scroll)');
    btnCompare.Layout.Row = 1; btnCompare.Layout.Column = 9;

    btnGrid = uibutton(toolbarGL, 'Text', 'Grid', ...
        'ButtonPushedFcn', callbacks.onThumbnailGrid, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Show thumbnail grid of all loaded images');
    btnGrid.Layout.Row = 1; btnGrid.Layout.Column = 10;

    btnEDSToolbar = uibutton(toolbarGL, 'state', 'Text', 'EDS', ...
        'ValueChangedFcn', callbacks.onEDSToolbarToggle, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Enable', 'off', ...
        'Tooltip', 'Enter/exit multi-channel EDS false-color composite mode');
    btnEDSToolbar.Layout.Row = 1; btnEDSToolbar.Layout.Column = 11;

    lblFilename = uilabel(toolbarGL, 'Text', '(no image loaded)', ...
        'FontSize', 11, ...
        'FontColor', [0.85 0.85 0.85], ...
        'HorizontalAlignment', 'left');
    lblFilename.Layout.Row = 1; lblFilename.Layout.Column = 12;

    btnPrefs = uibutton(toolbarGL, 'Text', char(9881), ...
        'ButtonPushedFcn', callbacks.onPreferences, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Preferences — default colormap, percentiles, export settings');
    btnPrefs.Layout.Row = 1; btnPrefs.Layout.Column = 14;
    btnThemeToggle = uibutton(toolbarGL, 'Text', char(9790), ...
        'ButtonPushedFcn', callbacks.onThemeToggle, ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'Tooltip', 'Toggle dark / light mode');
    btnThemeToggle.Layout.Row = 1; btnThemeToggle.Layout.Column = 15;
    btnShortcuts = uibutton(toolbarGL, 'Text', '?', ...
        'ButtonPushedFcn', @(~,~) callbacks.onShowEMShortcuts(), ...
        'BackgroundColor', BTN_TOOL, ...
        'FontColor', BTN_FG, ...
        'FontWeight', 'bold', ...
        'Tooltip', 'Keyboard shortcuts');
    btnShortcuts.Layout.Row = 1; btnShortcuts.Layout.Column = 16;

    % ── Output struct ──────────────────────────────────────────────────────
    s = struct( ...
        'toolbarGL',      toolbarGL, ...
        'lblFilename',    lblFilename, ...
        'ddRecent',       ddRecent, ...
        'btnCompare',     btnCompare, ...
        'btnGrid',        btnGrid, ...
        'btnEDSToolbar',  btnEDSToolbar, ...
        'btnThemeToggle', btnThemeToggle);
end
