function msg = shortcutsText()
%SHORTCUTSTEXT  Return the formatted keyboard shortcuts string for FermiViewer.
    msg = sprintf(['Keyboard Shortcuts\n\n' ...
        '── File ──────────────────────────────\n' ...
        'Ctrl+O                Open image files\n' ...
        'Ctrl+S                Save current image\n' ...
        'Ctrl+Shift+S          Save session\n' ...
        'Ctrl+Shift+L          Load session\n\n' ...
        '── View ──────────────────────────────\n' ...
        'A                     Auto-contrast\n' ...
        'F                     Fit image to window\n' ...
        'P                     Toggle pan mode\n' ...
        '+ / =                 Zoom in (2x)\n' ...
        '- / _                 Zoom out (2x)\n' ...
        'D                     Zoom to dimensions\n' ...
        'F5                    Refresh display\n\n' ...
        '── Navigation ────────────────────────\n' ...
        'Left / Right          Switch image\n' ...
        'Tab (compare)         Switch active panel\n' ...
        'Middle-drag           Pan (always, any mode)\n\n' ...
        '── Edit ──────────────────────────────\n' ...
        'Ctrl+Z                Undo filters\n' ...
        'Escape                Cancel capture / deselect\n' ...
        'Delete / Backspace    Remove selected annotation']);
end
