function msg = formatRoughnessResult(result, unit)
%FORMATROUGHNESSRESULT  Format surface roughness statistics for display.
    arguments
        result struct
        unit   char
    end
    msg = sprintf(['Surface Roughness\n\n' ...
        'Ra  = %.4g %s\nRq  = %.4g %s\nRz  = %.4g %s\n' ...
        'Rsk = %.4f\nRku = %.4f\nRp  = %.4g %s\nRv  = %.4g %s\n' ...
        'SAR = %.4f'], ...
        result.Ra, unit, result.Rq, unit, result.Rz, unit, ...
        result.Rsk, result.Rku, result.Rp, unit, result.Rv, unit, ...
        result.SAR);
end
