function h = buildGroupsBar(parentGL, ctx)
%BUILDGROUPSBAR  "Compare Groups" controls under the image list.
%
%   h = fermiViewer.groups.buildGroupsBar(parentGL, ctx) builds a compact
%   panel with a "Group Selected" button and two panel-binding dropdowns
%   (Left / Right). It is parented into a cell of the file-list grid and
%   wires its callbacks to fermiViewer.groups.dispatch, which mutates the
%   shared GroupModel handle (ctx.model) by reference.
%
%   ctx fields (from FermiViewer):
%     .model           fermiViewer.groups.GroupModel handle
%     .lbImages        image listbox
%     .setStatus       @(msg)
%     .setCompareIdxL  @(idx)   set + redraw left compare panel
%     .setCompareIdxR  @(idx)   set + redraw right compare panel
%     .fig             figure handle (name dialog parent; optional)
%     .tk              uxTokens struct for initial theming
%
%   Returns h with handles {panel, innerGL, btnCreate, btnDelete, ddLeft,
%   ddRight, lblL, lblR} so the caller can register them for theme toggles.
%
%   See also FERMIVIEWER.GROUPS.DISPATCH, FERMIVIEWER.GROUPS.GROUPMODEL

    tk = ctx.tk;

    panel = uipanel(parentGL, 'Title', 'Compare Groups', ...
        'FontSize', tk.font.title, ...
        'BackgroundColor', tk.color.bgPanel, ...
        'ForegroundColor', tk.color.text);

    innerGL = uigridlayout(panel, [3 3], ...
        'RowHeight',   {26, 24, 24}, ...
        'ColumnWidth', {52, '1x', 24}, ...
        'Padding',     [6 4 6 4], ...
        'RowSpacing',  3, 'ColumnSpacing', 4, ...
        'BackgroundColor', tk.color.bgPanel);

    % Row 1: create from current multi-selection (spans the label+field cols).
    btnCreate = uibutton(innerGL, 'Text', 'Group Selected', ...
        'FontSize', tk.font.body, ...
        'BackgroundColor', tk.color.btn.accent, 'FontColor', tk.color.btn.fg, ...
        'Tooltip', ['Make a named group from the images selected in the list ' ...
                    '(Ctrl/Shift-click to multi-select).']);
    btnCreate.Layout.Row = 1; btnCreate.Layout.Column = [1 2];

    % Row 1, col 3: delete the group shown in the Left dropdown.
    btnDelete = uibutton(innerGL, 'Text', '✕', ...
        'FontSize', tk.font.body, ...
        'BackgroundColor', tk.color.btn.tool, 'FontColor', tk.color.btn.fg, ...
        'Tooltip', 'Delete the group selected in the Left dropdown.');
    btnDelete.Layout.Row = 1; btnDelete.Layout.Column = 3;

    % Row 2: Left panel binding.
    lblL = uilabel(innerGL, 'Text', 'Left ◀', ...
        'FontSize', tk.font.label, 'FontColor', tk.color.text, ...
        'HorizontalAlignment', 'right');
    lblL.Layout.Row = 2; lblL.Layout.Column = 1;
    ddLeft = uidropdown(innerGL, 'Items', {'(all images)'}, 'ItemsData', {0}, ...
        'Value', 0, 'FontSize', tk.font.body, ...
        'BackgroundColor', tk.color.bgInput, 'FontColor', tk.color.text, ...
        'Tooltip', 'Images the Left compare panel cycles through.');
    ddLeft.Layout.Row = 2; ddLeft.Layout.Column = [2 3];

    % Row 3: Right panel binding.
    lblR = uilabel(innerGL, 'Text', 'Right ▶', ...
        'FontSize', tk.font.label, 'FontColor', tk.color.text, ...
        'HorizontalAlignment', 'right');
    lblR.Layout.Row = 3; lblR.Layout.Column = 1;
    ddRight = uidropdown(innerGL, 'Items', {'(all images)'}, 'ItemsData', {0}, ...
        'Value', 0, 'FontSize', tk.font.body, ...
        'BackgroundColor', tk.color.bgInput, 'FontColor', tk.color.text, ...
        'Tooltip', 'Images the Right compare panel cycles through.');
    ddRight.Layout.Row = 3; ddRight.Layout.Column = [2 3];

    % Full dispatch context = incoming ctx + the dropdowns we just made.
    dctx = ctx;
    dctx.ddLeft  = ddLeft;
    dctx.ddRight = ddRight;

    btnCreate.ButtonPushedFcn = @(~,~) fermiViewer.groups.dispatch('create', dctx);
    btnDelete.ButtonPushedFcn = @(~,~) fermiViewer.groups.dispatch('delete', dctx);
    ddLeft.ValueChangedFcn    = @(~,~) fermiViewer.groups.dispatch('assignL', dctx);
    ddRight.ValueChangedFcn   = @(~,~) fermiViewer.groups.dispatch('assignR', dctx);

    h = struct('panel', panel, 'innerGL', innerGL, 'btnCreate', btnCreate, ...
        'btnDelete', btnDelete, 'ddLeft', ddLeft, 'ddRight', ddRight, ...
        'lblL', lblL, 'lblR', lblR);
end
