function runNoiseEstimate(fig, filteredPixels, setStatus)
%RUNNOISEESTIMATE  Characterize image noise and recommend a filter.
%
%   Shows a modal alert with noise sigma, SNR, type, and suggested filter
%   parameters. Pure side-effect (status + alert), no appData mutation.

    if isempty(filteredPixels), return; end
    try
        r = imaging.noiseEstimate(filteredPixels, Method='both');
        msg = { ...
            sprintf('Noise σ = %.3f', r.sigma), ...
            sprintf('SNR = %.1f dB (%.1f linear)', r.snr, r.snrLinear), ...
            sprintf('Noise type: %s', r.noiseType), ...
            '', ...
            'Suggested filter:', ...
            sprintf('  Type: %s', r.suggestedFilter.type), ...
            sprintf('  σ = %.1f (Gaussian) or window = %d (median)', ...
                r.suggestedFilter.sigma, r.suggestedFilter.window)};
        fermiViewer.chrome.quietAlert(fig, strjoin(msg, '\n'), 'Noise Estimate', 'Icon', 'info');
        setStatus(sprintf('Noise: σ=%.3f, SNR=%.1fdB, type=%s', r.sigma, r.snr, r.noiseType));
    catch ME
        fermiViewer.chrome.quietAlert(fig, sprintf('Noise estimate failed:\n%s', ME.message), ...
            'Error', 'Icon', 'error');
    end
end
